"""
Manual AI — Professional server-side PDF export (AI Overview Visibility Report).

Generates a multi-page, branded PDF report that mirrors the entire Analytics
tab of the Manual AI dashboard at /manual-ai/. Designed to be "digno de
enviar a tu jefe o a tu cliente" — a report you can hand to a paying client
as-is.

Architecture mirrors the LLM Monitoring PDF export in `llm_monitoring_routes.py`
(`export_project_pdf`, lines 5635-6668) but with a cleaner service layer.

## Page structure (9 pages, 8 if clusters disabled)

    1. Cover / Project Details
    2. Executive Summary (6 KPIs)
    3. Trends Over Time (visibility chart + position distribution + events)
    4. Thematic Clusters Analysis    (skipped entirely if disabled)
    5. Competitive Analysis           (multi-series charts + comparison table)
    6. AI Overview Keywords Details   (dynamic competitor columns)
    7. Top Mentioned URLs in AI Overview
    8. Global AI Overview Domains Ranking
    9. AI Overview vs Organic Comparison  (the new flagship feature)

## Brand styling

Every page has a dark header bar (#161616) with the report title and a
Clicandseo logo watermark on the right, plus a footer with page number and
logo. Tables use alternating row colors, dark headers with white text,
colored cells for sentiment-like signals (green/yellow/red), and clickable
URL links in blue.

## Data sources (all read-only, no writes)

    - ProjectRepository.get_project_info
    - StatisticsService.get_project_statistics
    - StatisticsService.get_latest_overview_stats
    - StatisticsService.get_project_ai_overview_keywords_latest
    - StatisticsService.get_project_urls_ranking
    - StatisticsService.get_project_global_domains_ranking
    - StatisticsService.get_aio_vs_organic_comparison
    - ClusterService.get_cluster_statistics
    - CompetitorService.get_project_comparative_charts_data

All fetches are wrapped in try/except so a single data source failing does
not crash the whole PDF — the affected page renders a "No data available"
placeholder instead.
"""

import logging
from datetime import datetime
from io import BytesIO
from typing import Dict, List, Optional
from urllib.parse import urlparse

logger = logging.getLogger(__name__)


# ═══════════════════════════════════════════════════════════════════════════
#  Brand constants
# ═══════════════════════════════════════════════════════════════════════════

# Primary palette — matches the LLM Monitoring PDF and Clicandseo brand
_BRAND_DARK = '#161616'          # Near-black for headers and emphasis
_BRAND_ACCENT = '#D8F9B8'        # Bio-Lime — accent only on dark bg
_BRAND_WHITE = '#FFFFFF'

# Cell highlights
_CLR_GREEN_CELL = '#D1FAE5'      # Positive signal / brand domain row
_CLR_YELLOW_CELL = '#FEF3C7'     # Competitor row / warning
_CLR_BLUE_CELL = '#DBEAFE'       # Cited-only / info signal
_CLR_RED_CELL = '#FEE2E2'        # Negative signal
_CLR_GRAY_CELL = '#F3F4F6'       # Neutral / "neither"

# Typography + structure
_CLR_BODY = '#374151'            # Body text
_CLR_BORDER = '#E5E7EB'          # Table borders
_CLR_LIGHT_GRAY = '#9CA3AF'      # Muted / placeholders
_CLR_ROW_ALT = '#F9FAFB'         # Alternating row background
_CLR_DELTA_UP = '#059669'        # Positive delta
_CLR_DELTA_DOWN = '#DC2626'      # Negative delta

# Chart colors — match the UI 1:1 (from CompetitorService.get_project_comparative_charts_data)
_CHART_COLOR_PROJECT = '#5BF0AF'
_CHART_COLORS_COMPETITORS = ['#F0715B', '#1851F1', '#A1A9FF', '#8EAA96']

# Report title + footer
_REPORT_TITLE = 'AI Overview Visibility Report'
_FOOTER_BRAND = 'Generated by ClicAndSEO — AI Overview Monitor'


# ═══════════════════════════════════════════════════════════════════════════
#  Public entry point
# ═══════════════════════════════════════════════════════════════════════════

class ManualAiPdfExportService:
    """Generate a professional multi-page PDF report for a Manual AI project."""

    @staticmethod
    def generate_project_pdf(project_id: int, days: int = 30) -> BytesIO:
        """
        Build the full Manual AI PDF for a project and return it as a BytesIO.

        Args:
            project_id: Manual AI project ID
            days:       Lookback window in days (default 30, clamped to [1, 365])

        Returns:
            BytesIO positioned at 0 — ready to be passed to Flask's `send_file`.

        Raises:
            ImportError: if ReportLab is not installed (requirements.txt already
                        pins `reportlab==4.2.5`)
            ValueError:  if the project does not exist
        """
        # Validate params
        if days < 1:
            days = 1
        elif days > 365:
            days = 365

        logger.info(f"[PDF Export] Starting generation for project {project_id}, days={days}")

        # Import ReportLab lazily so `import manual_ai.services.pdf_export_service`
        # doesn't fail in environments where reportlab is missing (e.g. some
        # test setups). The route handler already catches ImportError.
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.units import cm
        from reportlab.platypus import SimpleDocTemplate

        # Fetch all data (defensive — one source failing does not kill the PDF)
        data = ManualAiPdfExportService._fetch_all_data(project_id, days)
        if not data.get('project_info'):
            raise ValueError(f"Project {project_id} not found")

        # Build styles
        styles = ManualAiPdfExportService._build_styles()

        # Build the document
        page_width, page_height = A4
        output = BytesIO()

        doc = SimpleDocTemplate(
            output,
            pagesize=A4,
            rightMargin=2 * cm,
            leftMargin=2 * cm,
            topMargin=2.2 * cm,
            bottomMargin=1.8 * cm,
            title=_REPORT_TITLE,
            author='ClicAndSEO',
            subject=f"AI Overview report — {data['project_info'].get('name', 'Project')}",
        )

        # Page chrome closures (need access to page_width / page_height)
        def _on_page(canvas_obj, doc_obj):
            ManualAiPdfExportService._draw_page_chrome(
                canvas_obj, doc_obj, page_width, page_height
            )

        elements = []

        # Build each page
        try:
            ManualAiPdfExportService._build_page1_cover(elements, data, styles, days)
            ManualAiPdfExportService._build_page2_executive_summary(elements, data, styles)
            ManualAiPdfExportService._build_page3_trends(elements, data, styles)

            # Page 4 is optional
            if ManualAiPdfExportService._clusters_have_data(data.get('clusters')):
                ManualAiPdfExportService._build_page4_clusters(elements, data, styles)

            ManualAiPdfExportService._build_page5_competitive(elements, data, styles)
            ManualAiPdfExportService._build_page6_keywords(elements, data, styles)
            ManualAiPdfExportService._build_page7_top_urls(elements, data, styles)
            ManualAiPdfExportService._build_page8_domains_ranking(elements, data, styles)
            ManualAiPdfExportService._build_page9_aio_vs_organic(elements, data, styles)
        except Exception as page_error:
            # If a page builder raises despite defensive handling, log and
            # continue — partial PDF is better than no PDF at all.
            logger.error(f"[PDF Export] Page builder error: {page_error}", exc_info=True)

        doc.build(elements, onFirstPage=_on_page, onLaterPages=_on_page)
        output.seek(0)

        size_kb = output.getbuffer().nbytes / 1024
        logger.info(f"[PDF Export] Generation complete for project {project_id}: {size_kb:.1f} KB")

        return output

    # ═══════════════════════════════════════════════════════════════════════
    #  Data fetching (one bundle, defensive)
    # ═══════════════════════════════════════════════════════════════════════

    @staticmethod
    def _fetch_all_data(project_id: int, days: int) -> Dict:
        """
        Fetch everything the PDF needs in one go. Every call is wrapped in
        try/except — if a service fails, the relevant key is set to a
        sensible empty value and the affected page builder renders a
        "No data" placeholder instead of crashing.
        """
        from manual_ai.models.project_repository import ProjectRepository
        from manual_ai.services.statistics_service import StatisticsService
        from manual_ai.services.cluster_service import ClusterService
        from manual_ai.services.competitor_service import CompetitorService

        data: Dict = {
            'project_id': project_id,
            'days': days,
            'project_info': None,
            'latest_overview': {},
            'project_stats': {},
            'clusters': {},
            'comparative': {},
            'keywords_latest': {},
            'top_urls': [],
            'global_domains': [],
            'aio_vs_organic': {},
        }

        try:
            data['project_info'] = ProjectRepository.get_project_info(project_id)
        except Exception as e:
            logger.error(f"[PDF Export] Failed to fetch project_info: {e}")
            return data

        if not data['project_info']:
            return data

        # StatisticsService calls
        try:
            data['latest_overview'] = StatisticsService.get_latest_overview_stats(project_id) or {}
        except Exception as e:
            logger.warning(f"[PDF Export] get_latest_overview_stats failed: {e}")

        try:
            data['project_stats'] = StatisticsService.get_project_statistics(project_id, days) or {}
        except Exception as e:
            logger.warning(f"[PDF Export] get_project_statistics failed: {e}")

        try:
            data['keywords_latest'] = StatisticsService.get_project_ai_overview_keywords_latest(project_id) or {}
        except Exception as e:
            logger.warning(f"[PDF Export] get_project_ai_overview_keywords_latest failed: {e}")

        try:
            data['top_urls'] = StatisticsService.get_project_urls_ranking(project_id, days, limit=20) or []
        except Exception as e:
            logger.warning(f"[PDF Export] get_project_urls_ranking failed: {e}")

        try:
            data['global_domains'] = StatisticsService.get_project_global_domains_ranking(project_id, days) or []
        except Exception as e:
            logger.warning(f"[PDF Export] get_project_global_domains_ranking failed: {e}")

        try:
            data['aio_vs_organic'] = StatisticsService.get_aio_vs_organic_comparison(project_id, days) or {}
        except Exception as e:
            logger.warning(f"[PDF Export] get_aio_vs_organic_comparison failed: {e}")

        # ClusterService
        try:
            data['clusters'] = ClusterService.get_cluster_statistics(project_id, days) or {}
        except Exception as e:
            logger.warning(f"[PDF Export] get_cluster_statistics failed: {e}")

        # CompetitorService
        try:
            data['comparative'] = CompetitorService.get_project_comparative_charts_data(project_id, days) or {}
        except Exception as e:
            logger.warning(f"[PDF Export] get_project_comparative_charts_data failed: {e}")

        return data

    # ═══════════════════════════════════════════════════════════════════════
    #  Styles + color helpers
    # ═══════════════════════════════════════════════════════════════════════

    @staticmethod
    def _build_styles() -> Dict:
        """Build the reusable ParagraphStyle and color constants."""
        from reportlab.lib import colors
        from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet

        base = getSampleStyleSheet()

        CLR_DARK = colors.HexColor(_BRAND_DARK)
        CLR_BODY_C = colors.HexColor(_CLR_BODY)
        CLR_LIGHT = colors.HexColor(_CLR_LIGHT_GRAY)

        return {
            # Colors (ReportLab HexColor objects)
            'CLR_DARK': CLR_DARK,
            'CLR_WHITE': colors.white,
            'CLR_ACCENT': colors.HexColor(_BRAND_ACCENT),
            'CLR_GREEN_CELL': colors.HexColor(_CLR_GREEN_CELL),
            'CLR_YELLOW_CELL': colors.HexColor(_CLR_YELLOW_CELL),
            'CLR_BLUE_CELL': colors.HexColor(_CLR_BLUE_CELL),
            'CLR_RED_CELL': colors.HexColor(_CLR_RED_CELL),
            'CLR_GRAY_CELL': colors.HexColor(_CLR_GRAY_CELL),
            'CLR_BODY': CLR_BODY_C,
            'CLR_BORDER': colors.HexColor(_CLR_BORDER),
            'CLR_LIGHT_GRAY': CLR_LIGHT,
            'CLR_ROW_ALT': colors.HexColor(_CLR_ROW_ALT),
            'CLR_DELTA_UP': colors.HexColor(_CLR_DELTA_UP),
            'CLR_DELTA_DOWN': colors.HexColor(_CLR_DELTA_DOWN),
            'CLR_LINK': colors.HexColor('#2563EB'),
            'CLR_SUBHEADER': colors.HexColor('#F3F4F6'),

            # Paragraph styles
            'title': ParagraphStyle(
                'PDFTitle', parent=base['Heading1'],
                fontSize=22, fontName='Helvetica-Bold',
                textColor=CLR_DARK, spaceAfter=6, spaceBefore=0,
            ),
            'project': ParagraphStyle(
                'PDFProject', parent=base['Heading1'],
                fontSize=18, fontName='Helvetica-Bold',
                textColor=CLR_DARK, spaceAfter=4,
            ),
            'period': ParagraphStyle(
                'PDFPeriod', parent=base['Normal'],
                fontSize=10, fontName='Helvetica',
                textColor=CLR_LIGHT, spaceAfter=14,
            ),
            'description': ParagraphStyle(
                'PDFDescription', parent=base['Normal'],
                fontSize=10, fontName='Helvetica-Oblique',
                textColor=CLR_BODY_C, spaceAfter=12, leading=14,
            ),
            'section': ParagraphStyle(
                'PDFSection', parent=base['Heading2'],
                fontSize=14, fontName='Helvetica-Bold',
                textColor=CLR_DARK, spaceAfter=8, spaceBefore=12,
            ),
            'subsection': ParagraphStyle(
                'PDFSubsection', parent=base['Heading3'],
                fontSize=11, fontName='Helvetica-Bold',
                textColor=CLR_BODY_C, spaceAfter=6, spaceBefore=8,
            ),
            'body': ParagraphStyle(
                'PDFBody', parent=base['Normal'],
                fontSize=9, fontName='Helvetica',
                textColor=CLR_BODY_C, spaceAfter=4, leading=12,
            ),
            'body_small': ParagraphStyle(
                'PDFBodySmall', parent=base['Normal'],
                fontSize=8, fontName='Helvetica',
                textColor=CLR_BODY_C, spaceAfter=2, leading=10,
            ),
            'caption': ParagraphStyle(
                'PDFCaption', parent=base['Normal'],
                fontSize=8, fontName='Helvetica-Oblique',
                textColor=CLR_LIGHT, spaceAfter=4, leading=10, alignment=TA_CENTER,
            ),
            'kpi_label': ParagraphStyle(
                'KPILabel', parent=base['Normal'],
                fontSize=8, fontName='Helvetica',
                textColor=CLR_LIGHT, spaceAfter=0, alignment=TA_CENTER,
            ),
            'kpi_value': ParagraphStyle(
                'KPIValue', parent=base['Normal'],
                fontSize=18, fontName='Helvetica-Bold',
                textColor=CLR_DARK, spaceAfter=0, alignment=TA_CENTER,
            ),
            'no_data': ParagraphStyle(
                'NoData', parent=base['Normal'],
                fontSize=10, fontName='Helvetica-Oblique',
                textColor=CLR_LIGHT, spaceAfter=8,
                alignment=TA_CENTER, leading=14,
            ),
            'url_link': ParagraphStyle(
                'URLLink', parent=base['Normal'],
                fontSize=8, fontName='Helvetica',
                textColor=colors.HexColor('#2563EB'), spaceAfter=2, leading=10,
            ),
        }

    @staticmethod
    def _base_table_style(num_rows: int, styles: Dict) -> list:
        """
        Standard dark-header table style with alternating rows.
        Callers can append their own overrides.
        """
        cmds = [
            ('BACKGROUND', (0, 0), (-1, 0), styles['CLR_DARK']),
            ('TEXTCOLOR', (0, 0), (-1, 0), styles['CLR_WHITE']),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 8),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
            ('TOPPADDING', (0, 0), (-1, 0), 8),
            ('TEXTCOLOR', (0, 1), (-1, -1), styles['CLR_BODY']),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, styles['CLR_BORDER']),
            ('TOPPADDING', (0, 1), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 1), (-1, -1), 6),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]
        # Alternating row colors
        for i in range(1, num_rows):
            if i % 2 == 0:
                cmds.append(('BACKGROUND', (0, i), (-1, i), styles['CLR_ROW_ALT']))
        return cmds

    # ═══════════════════════════════════════════════════════════════════════
    #  Generic helpers
    # ═══════════════════════════════════════════════════════════════════════

    @staticmethod
    def _truncate(text, max_len: int = 60) -> str:
        """Truncate text to max_len with ellipsis."""
        if text is None:
            return 'N/A'
        text = str(text)
        if len(text) <= max_len:
            return text
        return text[:max_len - 3] + '...'

    @staticmethod
    def _escape_html(text) -> str:
        """Escape text for ReportLab Paragraph (HTML-like markup)."""
        if text is None:
            return ''
        s = str(text)
        return (
            s.replace('&', '&amp;')
             .replace('<', '&lt;')
             .replace('>', '&gt;')
        )

    @staticmethod
    def _fmt_num(value, decimals: int = 0, default: str = 'N/A') -> str:
        """Format a number to a fixed number of decimals, handling None."""
        if value is None:
            return default
        try:
            v = float(value)
            if decimals == 0:
                return f"{int(round(v)):,}"
            return f"{v:.{decimals}f}"
        except (TypeError, ValueError):
            return default

    @staticmethod
    def _fmt_pct(value, decimals: int = 1, default: str = 'N/A') -> str:
        """Format a value as percentage."""
        if value is None:
            return default
        try:
            return f"{float(value):.{decimals}f}%"
        except (TypeError, ValueError):
            return default

    @staticmethod
    def _domain_of(url: str) -> Optional[str]:
        """Extract a canonical domain from a URL (no scheme, no www)."""
        if not url:
            return None
        try:
            parsed = urlparse(url if '://' in url else f'https://{url}')
            host = (parsed.netloc or '').lower()
            if host.startswith('www.'):
                host = host[4:]
            return host or None
        except Exception:
            return None

    @staticmethod
    def _clusters_have_data(clusters_data: Dict) -> bool:
        """Return True if the clusters page should be rendered."""
        if not clusters_data:
            return False
        if not clusters_data.get('enabled'):
            return False
        if not clusters_data.get('table_data'):
            return False
        return True

    # ═══════════════════════════════════════════════════════════════════════
    #  Brand chrome — header bar, footer, logo watermark
    #  Adapted from llm_monitoring_routes.py:5964-6013
    # ═══════════════════════════════════════════════════════════════════════

    @staticmethod
    def _draw_logo_watermark(canvas_obj, x, y, font_size=12, dark_bg=False):
        """
        Draw the 'Clicandseo.' wordmark as styled text.
        Matches the brand SVG: 'Clic' bold + 'and' faded + 'seo' bold + '.' accent.
        """
        from reportlab.lib import colors

        text_color = colors.white if dark_bg else colors.HexColor('#0F172A')
        faded_color = colors.Color(1, 1, 1, 0.5) if dark_bg else colors.Color(0.06, 0.09, 0.16, 0.5)
        accent_color = colors.HexColor(_BRAND_ACCENT)

        canvas_obj.setFont('Helvetica-Bold', font_size)
        canvas_obj.setFillColor(text_color)
        canvas_obj.drawString(x, y, 'Clic')
        w_clic = canvas_obj.stringWidth('Clic', 'Helvetica-Bold', font_size)

        canvas_obj.setFont('Helvetica', font_size)
        canvas_obj.setFillColor(faded_color)
        canvas_obj.drawString(x + w_clic, y, 'and')
        w_and = canvas_obj.stringWidth('and', 'Helvetica', font_size)

        canvas_obj.setFont('Helvetica-Bold', font_size)
        canvas_obj.setFillColor(text_color)
        canvas_obj.drawString(x + w_clic + w_and, y, 'seo')
        w_seo = canvas_obj.stringWidth('seo', 'Helvetica-Bold', font_size)

        canvas_obj.setFillColor(accent_color)
        canvas_obj.drawString(x + w_clic + w_and + w_seo, y, '.')

    @staticmethod
    def _draw_page_chrome(canvas_obj, doc_obj, page_width, page_height):
        """Shared header bar + footer + logo watermark for every page."""
        from reportlab.lib import colors
        from reportlab.lib.units import cm

        canvas_obj.saveState()

        # Dark header bar
        canvas_obj.setFillColor(colors.HexColor(_BRAND_DARK))
        canvas_obj.rect(0, page_height - 1.2 * cm, page_width, 1.2 * cm, fill=1, stroke=0)
        canvas_obj.setFillColor(colors.white)
        canvas_obj.setFont('Helvetica-Bold', 10)
        canvas_obj.drawString(2 * cm, page_height - 0.85 * cm, _REPORT_TITLE)

        # Header logo (dark bg → white text)
        ManualAiPdfExportService._draw_logo_watermark(
            canvas_obj, page_width - 4.5 * cm, page_height - 0.85 * cm,
            font_size=10, dark_bg=True,
        )

        # Footer text
        canvas_obj.setFillColor(colors.HexColor(_CLR_LIGHT_GRAY))
        canvas_obj.setFont('Helvetica', 8)
        footer_text = f"{_FOOTER_BRAND} | Page {doc_obj.page}"
        canvas_obj.drawCentredString(page_width / 2, 1 * cm, footer_text)

        # Watermark logo bottom-right (light bg → dark text)
        ManualAiPdfExportService._draw_logo_watermark(
            canvas_obj, page_width - 4 * cm, 0.5 * cm,
            font_size=11, dark_bg=False,
        )

        canvas_obj.restoreState()

    # ═══════════════════════════════════════════════════════════════════════
    #  Page 1 — Cover / Project Details
    # ═══════════════════════════════════════════════════════════════════════

    @staticmethod
    def _build_page1_cover(elements: list, data: Dict, styles: Dict, days: int):
        from reportlab.lib.units import cm
        from reportlab.platypus import Paragraph, Spacer, Table, TableStyle

        project = data['project_info']
        clusters = data.get('clusters') or {}
        latest = data.get('latest_overview') or {}

        name = project.get('name', 'Project')
        description = project.get('description') or ''
        domain = project.get('domain', 'N/A')
        country = project.get('country_code', 'N/A')
        competitors = project.get('selected_competitors') or []
        clusters_enabled = bool(clusters.get('enabled'))
        clusters_count = int(clusters.get('total_clusters') or 0) if clusters_enabled else 0
        last_analysis = latest.get('last_analysis_date')

        elements.append(Spacer(1, 0.5 * cm))
        elements.append(Paragraph(_REPORT_TITLE, styles['title']))
        elements.append(Spacer(1, 0.3 * cm))
        elements.append(Paragraph(
            ManualAiPdfExportService._escape_html(name), styles['project']
        ))
        elements.append(Paragraph(
            f"Period: Last {days} days  |  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            styles['period']
        ))

        if description:
            elements.append(Paragraph(
                ManualAiPdfExportService._escape_html(description),
                styles['description']
            ))

        elements.append(Spacer(1, 0.6 * cm))

        # Project Details table
        elements.append(Paragraph("Project Details", styles['section']))

        details_rows = [
            ['Field', 'Value'],
            ['Domain', domain or 'N/A'],
            ['Country', country or 'N/A'],
            ['Period analyzed', f"Last {days} days"],
            ['Competitors tracked', str(len(competitors))],
            ['Thematic clusters',
             f"Enabled ({clusters_count} clusters)" if clusters_enabled else 'Disabled'],
            ['Last analysis',
             str(last_analysis) if last_analysis else 'No data yet'],
        ]

        details_table = Table(details_rows, colWidths=[5 * cm, 10 * cm])
        ds = ManualAiPdfExportService._base_table_style(len(details_rows), styles)
        ds.append(('ALIGN', (0, 1), (0, -1), 'LEFT'))
        ds.append(('ALIGN', (1, 1), (1, -1), 'LEFT'))
        ds.append(('FONTNAME', (0, 1), (0, -1), 'Helvetica-Bold'))
        details_table.setStyle(TableStyle(ds))
        elements.append(details_table)
        elements.append(Spacer(1, 0.6 * cm))

        # Competitors section
        if competitors:
            elements.append(Paragraph("Competitors Tracked", styles['subsection']))
            elements.append(Spacer(1, 0.15 * cm))

            comp_rows = [['#', 'Domain']]
            for i, comp in enumerate(competitors, start=1):
                # selected_competitors is a list of plain strings in Manual AI
                comp_rows.append([str(i), str(comp) if comp else 'N/A'])

            comp_table = Table(comp_rows, colWidths=[1.5 * cm, 13.5 * cm])
            cs = ManualAiPdfExportService._base_table_style(len(comp_rows), styles)
            cs.append(('ALIGN', (1, 1), (1, -1), 'LEFT'))
            comp_table.setStyle(TableStyle(cs))
            elements.append(comp_table)
        else:
            elements.append(Paragraph("Competitors Tracked", styles['subsection']))
            elements.append(Paragraph(
                "No competitors configured for this project.", styles['no_data']
            ))

    # ═══════════════════════════════════════════════════════════════════════
    #  Page 2 — Executive Summary (6 KPIs)
    # ═══════════════════════════════════════════════════════════════════════

    @staticmethod
    def _build_page2_executive_summary(elements: list, data: Dict, styles: Dict):
        from reportlab.lib.units import cm
        from reportlab.platypus import PageBreak, Paragraph, Spacer, Table, TableStyle

        elements.append(PageBreak())
        elements.append(Spacer(1, 0.3 * cm))
        elements.append(Paragraph("Executive Summary", styles['section']))

        latest = data.get('latest_overview') or {}
        last_analysis = latest.get('last_analysis_date')
        subtitle = (
            f"Overview metrics as of the latest analysis ({last_analysis})"
            if last_analysis
            else "Overview metrics — no analysis data available yet"
        )
        elements.append(Paragraph(subtitle, styles['body']))
        elements.append(Spacer(1, 0.5 * cm))

        # 6 KPIs in a 3-col × 2-row grid
        total_kw = int(latest.get('total_keywords') or 0)
        total_ai_kw = int(latest.get('total_ai_keywords') or 0)
        aio_weight = latest.get('aio_weight_percentage')
        total_mentions = int(latest.get('total_mentions') or 0)
        visibility = latest.get('visibility_percentage')
        avg_position = latest.get('avg_position')

        kpis = [
            ('Total Keywords', ManualAiPdfExportService._fmt_num(total_kw)),
            ('AI Overview Results', ManualAiPdfExportService._fmt_num(total_ai_kw)),
            ('AI Overview Weight',
             ManualAiPdfExportService._fmt_pct(aio_weight, decimals=0)),
            ('Domain Mentions', ManualAiPdfExportService._fmt_num(total_mentions)),
            ('Visibility',
             ManualAiPdfExportService._fmt_pct(visibility, decimals=0)),
            ('Avg Position (when mentioned)',
             f"#{float(avg_position):.1f}" if avg_position else 'N/A'),
        ]

        # Build a 3-col × 2-row table where each cell is a KPI box
        # (value on top, label below). We render it as a 4-row Table:
        # row 0 = values row 1, row 1 = labels row 1, row 2 = values row 2, row 3 = labels row 2.
        kpi_data = [
            [
                Paragraph(f"<b>{kpis[0][1]}</b>", styles['kpi_value']),
                Paragraph(f"<b>{kpis[1][1]}</b>", styles['kpi_value']),
                Paragraph(f"<b>{kpis[2][1]}</b>", styles['kpi_value']),
            ],
            [
                Paragraph(kpis[0][0], styles['kpi_label']),
                Paragraph(kpis[1][0], styles['kpi_label']),
                Paragraph(kpis[2][0], styles['kpi_label']),
            ],
            [
                Paragraph(f"<b>{kpis[3][1]}</b>", styles['kpi_value']),
                Paragraph(f"<b>{kpis[4][1]}</b>", styles['kpi_value']),
                Paragraph(f"<b>{kpis[5][1]}</b>", styles['kpi_value']),
            ],
            [
                Paragraph(kpis[3][0], styles['kpi_label']),
                Paragraph(kpis[4][0], styles['kpi_label']),
                Paragraph(kpis[5][0], styles['kpi_label']),
            ],
        ]

        col_width = (17.0 / 3) * cm
        kpi_table = Table(
            kpi_data,
            colWidths=[col_width, col_width, col_width],
            rowHeights=[1.3 * cm, 0.6 * cm, 1.3 * cm, 0.6 * cm],
        )
        kpi_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('BOX', (0, 0), (0, 1), 1, styles['CLR_BORDER']),
            ('BOX', (1, 0), (1, 1), 1, styles['CLR_BORDER']),
            ('BOX', (2, 0), (2, 1), 1, styles['CLR_BORDER']),
            ('BOX', (0, 2), (0, 3), 1, styles['CLR_BORDER']),
            ('BOX', (1, 2), (1, 3), 1, styles['CLR_BORDER']),
            ('BOX', (2, 2), (2, 3), 1, styles['CLR_BORDER']),
            ('BACKGROUND', (0, 0), (-1, 1), styles['CLR_SUBHEADER']),
            ('BACKGROUND', (0, 2), (-1, 3), styles['CLR_SUBHEADER']),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        elements.append(kpi_table)

        elements.append(Spacer(1, 0.6 * cm))

        # Narrative paragraph summarizing the numbers
        narrative_lines = []
        if total_kw > 0:
            narrative_lines.append(
                f"This project tracks <b>{total_kw}</b> keywords."
            )
        if total_ai_kw > 0:
            aio_w_str = ManualAiPdfExportService._fmt_pct(aio_weight, decimals=0)
            narrative_lines.append(
                f"Out of those, <b>{total_ai_kw}</b> currently trigger an AI Overview "
                f"({aio_w_str} AI Overview weight)."
            )
        if total_mentions > 0:
            vis_str = ManualAiPdfExportService._fmt_pct(visibility, decimals=0)
            narrative_lines.append(
                f"Your domain is mentioned in <b>{total_mentions}</b> of those "
                f"AI Overview results — a visibility rate of <b>{vis_str}</b>."
            )
        if avg_position is not None:
            narrative_lines.append(
                f"When your domain is mentioned, its average position inside "
                f"the AI Overview is <b>#{float(avg_position):.1f}</b>."
            )

        if narrative_lines:
            elements.append(Paragraph(' '.join(narrative_lines), styles['body']))
        elif total_kw == 0:
            elements.append(Paragraph(
                "No analysis data available for this project yet. Run an analysis to populate these metrics.",
                styles['no_data']
            ))

    # ═══════════════════════════════════════════════════════════════════════
    #  Page 3 — Trends Over Time
    # ═══════════════════════════════════════════════════════════════════════

    @staticmethod
    def _build_page3_trends(elements: list, data: Dict, styles: Dict):
        from reportlab.lib import colors
        from reportlab.lib.units import cm
        from reportlab.platypus import PageBreak, Paragraph, Spacer, Table, TableStyle

        elements.append(PageBreak())
        elements.append(Spacer(1, 0.3 * cm))
        elements.append(Paragraph("Trends Over Time", styles['section']))

        project_stats = data.get('project_stats') or {}
        visibility_data = project_stats.get('visibility_chart') or []
        positions_data = project_stats.get('positions_chart') or []
        events_data = project_stats.get('events') or []

        # ── Chart 1: Domain Visibility Over Time ──
        elements.append(Paragraph("Domain Visibility Over Time", styles['subsection']))

        if len(visibility_data) >= 2:
            chart = ManualAiPdfExportService._build_visibility_linechart(
                visibility_data, styles
            )
            if chart is not None:
                elements.append(chart)
            else:
                elements.append(Paragraph("Unable to render visibility chart.", styles['no_data']))
        else:
            elements.append(Paragraph(
                "Not enough data points yet to plot visibility over time.",
                styles['no_data']
            ))

        elements.append(Spacer(1, 0.6 * cm))

        # ── Chart 2: Position Distribution (aggregated totals) ──
        elements.append(Paragraph("Position Distribution", styles['subsection']))

        if positions_data:
            # Aggregate totals across the period
            total_pos = {
                'pos_1_3': 0, 'pos_4_10': 0, 'pos_11_20': 0, 'pos_21_plus': 0
            }
            for row in positions_data:
                for k in total_pos:
                    total_pos[k] += int(row.get(k) or 0)

            pos_rows = [
                ['Position Range', 'Occurrences', 'Share'],
            ]
            total_all = sum(total_pos.values())
            buckets = [
                ('Top 3 (positions 1-3)', total_pos['pos_1_3'], _CLR_GREEN_CELL),
                ('Positions 4-10', total_pos['pos_4_10'], _CLR_YELLOW_CELL),
                ('Positions 11-20', total_pos['pos_11_20'], _CLR_BLUE_CELL),
                ('Beyond position 20', total_pos['pos_21_plus'], _CLR_GRAY_CELL),
            ]
            for label, count, _clr in buckets:
                share = f"{(count / total_all * 100):.1f}%" if total_all > 0 else '0.0%'
                pos_rows.append([label, str(count), share])

            pos_table = Table(pos_rows, colWidths=[8 * cm, 4 * cm, 4 * cm])
            ps = ManualAiPdfExportService._base_table_style(len(pos_rows), styles)
            ps.append(('ALIGN', (0, 1), (0, -1), 'LEFT'))
            # Color-code rows
            for i, (label, count, clr_hex) in enumerate(buckets):
                if count > 0:
                    ps.append((
                        'BACKGROUND', (0, i + 1), (-1, i + 1), colors.HexColor(clr_hex)
                    ))
            pos_table.setStyle(TableStyle(ps))
            elements.append(pos_table)
        else:
            elements.append(Paragraph(
                "No position data available for this period.",
                styles['no_data']
            ))

        elements.append(Spacer(1, 0.5 * cm))

        # ── Period events mini-table ──
        if events_data:
            elements.append(Paragraph("Period Events", styles['subsection']))

            evt_rows = [['Date', 'Type', 'Description']]
            shown = events_data[:8]
            for e in shown:
                date_str = str(e.get('event_date', ''))
                evt_type = str(e.get('event_type', ''))
                desc = e.get('event_title') or e.get('event_description') or ''
                evt_rows.append([
                    date_str,
                    evt_type,
                    ManualAiPdfExportService._truncate(desc, 60),
                ])

            evt_table = Table(evt_rows, colWidths=[3 * cm, 3.5 * cm, 9.5 * cm])
            es = ManualAiPdfExportService._base_table_style(len(evt_rows), styles)
            es.append(('ALIGN', (0, 1), (-1, -1), 'LEFT'))
            evt_table.setStyle(TableStyle(es))
            elements.append(evt_table)

            if len(events_data) > 8:
                elements.append(Paragraph(
                    f"+{len(events_data) - 8} more events in the period",
                    styles['caption']
                ))

    @staticmethod
    def _build_visibility_linechart(visibility_data: List[Dict], styles: Dict):
        """Build a single-series line chart for domain visibility over time."""
        from reportlab.graphics.shapes import Drawing, Rect, String
        from reportlab.graphics.charts.lineplots import LinePlot
        from reportlab.graphics.widgets.markers import makeMarker
        from reportlab.lib import colors
        from reportlab.lib.units import cm

        # Filter rows with numeric visibility
        points = []
        dates = []
        for i, row in enumerate(visibility_data):
            pct = row.get('visibility_pct')
            if pct is None:
                continue
            try:
                points.append((i, float(pct)))
                dates.append(str(row.get('analysis_date', '')))
            except (TypeError, ValueError):
                continue

        if len(points) < 2:
            return None

        chart_w = 17 * cm
        chart_h = 7 * cm
        drawing = Drawing(float(chart_w), float(chart_h))

        # Background
        drawing.add(Rect(
            0, 0, float(chart_w), float(chart_h),
            fillColor=colors.HexColor('#FAFAFA'), strokeColor=None,
        ))

        # Re-normalize x values to 0-based index after filtering
        plot_data = [[(new_i, y) for new_i, (_, y) in enumerate(points)]]

        lp = LinePlot()
        lp.x = 40
        lp.y = 30
        lp.width = float(chart_w) - 60
        lp.height = float(chart_h) - 55
        lp.data = plot_data

        lp.lines[0].strokeColor = colors.HexColor(_CHART_COLOR_PROJECT)
        lp.lines[0].strokeWidth = 2.5
        lp.lines[0].symbol = makeMarker('Circle')
        lp.lines[0].symbol.size = 4
        lp.lines[0].symbol.fillColor = colors.HexColor(_CHART_COLOR_PROJECT)

        n = len(points)
        tick_step = max(1, n // 8)
        label_format_dates = dates  # closure reference for the lambda

        lp.xValueAxis.valueMin = 0
        lp.xValueAxis.valueMax = max(n - 1, 1)
        lp.xValueAxis.valueSteps = list(range(0, n, tick_step))
        lp.xValueAxis.labelTextFormat = (
            lambda v, _d=label_format_dates:
            _d[int(v)][-5:] if 0 <= int(v) < len(_d) else ''
        )
        lp.xValueAxis.labels.fontSize = 7
        lp.xValueAxis.labels.angle = 0
        lp.xValueAxis.strokeColor = colors.HexColor('#E5E7EB')

        lp.yValueAxis.valueMin = 0
        lp.yValueAxis.valueMax = 100
        lp.yValueAxis.valueStep = 20
        lp.yValueAxis.labelTextFormat = '%d%%'
        lp.yValueAxis.labels.fontSize = 7
        lp.yValueAxis.strokeColor = colors.HexColor('#E5E7EB')
        lp.yValueAxis.gridStrokeColor = colors.HexColor('#F3F4F6')
        lp.yValueAxis.visibleGrid = 1

        drawing.add(lp)

        # Legend at bottom-left
        drawing.add(Rect(40, 5, 8, 8, fillColor=colors.HexColor(_CHART_COLOR_PROJECT), strokeColor=None))
        drawing.add(String(52, 6, 'VISIBILITY %', fontSize=7, fillColor=colors.HexColor(_CLR_LIGHT_GRAY)))

        return drawing

    # ═══════════════════════════════════════════════════════════════════════
    #  Page 4 — Thematic Clusters Analysis (optional)
    # ═══════════════════════════════════════════════════════════════════════

    @staticmethod
    def _build_page4_clusters(elements: list, data: Dict, styles: Dict):
        from reportlab.graphics.charts.barcharts import VerticalBarChart
        from reportlab.graphics.shapes import Drawing, Rect, String
        from reportlab.lib import colors
        from reportlab.lib.units import cm
        from reportlab.platypus import PageBreak, Paragraph, Spacer, Table, TableStyle

        elements.append(PageBreak())
        elements.append(Spacer(1, 0.3 * cm))
        elements.append(Paragraph("Thematic Clusters Analysis", styles['section']))
        elements.append(Paragraph(
            "Your keywords grouped by topic clusters, showing how each cluster performs in AI Overview.",
            styles['body']
        ))
        elements.append(Spacer(1, 0.4 * cm))

        clusters = data.get('clusters') or {}
        chart_data = clusters.get('chart_data') or {}
        table_data = clusters.get('table_data') or []

        # ── Bar chart: keywords with AI Overview vs brand mentions ──
        labels = chart_data.get('labels') or []
        kw_with_aio = chart_data.get('keywords_with_ai_overview') or []
        mentions = chart_data.get('mentions') or []

        if labels and kw_with_aio:
            chart_w = 17 * cm
            chart_h = 7 * cm
            drawing = Drawing(float(chart_w), float(chart_h))
            drawing.add(Rect(
                0, 0, float(chart_w), float(chart_h),
                fillColor=colors.HexColor('#FAFAFA'), strokeColor=None,
            ))

            bc = VerticalBarChart()
            bc.x = 40
            bc.y = 35
            bc.width = float(chart_w) - 60
            bc.height = float(chart_h) - 70
            bc.data = [kw_with_aio, mentions]
            bc.categoryAxis.categoryNames = [
                ManualAiPdfExportService._truncate(l, 14) for l in labels
            ]
            bc.categoryAxis.labels.fontSize = 7
            bc.categoryAxis.labels.angle = 20
            bc.categoryAxis.labels.dy = -5
            bc.categoryAxis.strokeColor = colors.HexColor('#E5E7EB')
            bc.valueAxis.valueMin = 0
            bc.valueAxis.valueStep = max(1, (max(kw_with_aio + mentions) // 5) or 1)
            bc.valueAxis.labels.fontSize = 7
            bc.valueAxis.strokeColor = colors.HexColor('#E5E7EB')
            bc.valueAxis.gridStrokeColor = colors.HexColor('#F3F4F6')
            bc.valueAxis.visibleGrid = 1

            # Colors for the two series
            bc.bars[0].fillColor = colors.HexColor('#1851F1')  # KW with AI Overview
            bc.bars[1].fillColor = colors.HexColor(_CHART_COLOR_PROJECT)  # Brand mentions
            bc.bars.strokeColor = None
            bc.barSpacing = 2
            bc.groupSpacing = 12

            drawing.add(bc)

            # Legend
            drawing.add(Rect(40, 8, 8, 8, fillColor=colors.HexColor('#1851F1'), strokeColor=None))
            drawing.add(String(52, 9, 'KEYWORDS WITH AIO', fontSize=7, fillColor=colors.HexColor(_CLR_LIGHT_GRAY)))
            drawing.add(Rect(200, 8, 8, 8, fillColor=colors.HexColor(_CHART_COLOR_PROJECT), strokeColor=None))
            drawing.add(String(212, 9, 'BRAND MENTIONS', fontSize=7, fillColor=colors.HexColor(_CLR_LIGHT_GRAY)))

            elements.append(drawing)

        elements.append(Spacer(1, 0.6 * cm))

        # ── Cluster performance table ──
        if table_data:
            elements.append(Paragraph("Cluster Performance", styles['subsection']))

            t_rows = [['Cluster', 'Total Kw', 'Kw w/ AIO', 'AI Weight', 'Mentions', 'Brand Visibility']]
            for row in table_data:
                t_rows.append([
                    ManualAiPdfExportService._truncate(row.get('cluster_name', ''), 22),
                    str(row.get('total_keywords', 0)),
                    str(row.get('keywords_with_ai_overview', 0)),
                    f"{row.get('ai_weight_percentage', 0):.1f}%",
                    str(row.get('mentions_count', 0)),
                    f"{row.get('brand_visibility_percentage', 0):.1f}%",
                ])

            t_widths = [5 * cm, 1.8 * cm, 2 * cm, 2 * cm, 1.8 * cm, 3 * cm]
            t_table = Table(t_rows, colWidths=t_widths)
            ts = ManualAiPdfExportService._base_table_style(len(t_rows), styles)
            ts.append(('ALIGN', (0, 1), (0, -1), 'LEFT'))
            t_table.setStyle(TableStyle(ts))
            elements.append(t_table)

            elements.append(Spacer(1, 0.3 * cm))
            elements.append(Paragraph(
                "Full keyword-to-cluster mapping is available in the Excel export.",
                styles['caption']
            ))
        else:
            elements.append(Paragraph(
                "No cluster performance data available for this period.",
                styles['no_data']
            ))

    # ═══════════════════════════════════════════════════════════════════════
    #  Page 5 — Competitive Analysis
    # ═══════════════════════════════════════════════════════════════════════

    @staticmethod
    def _build_page5_competitive(elements: list, data: Dict, styles: Dict):
        from reportlab.lib.units import cm
        from reportlab.platypus import PageBreak, Paragraph, Spacer, Table, TableStyle

        elements.append(PageBreak())
        elements.append(Spacer(1, 0.3 * cm))
        elements.append(Paragraph("Competitive Analysis", styles['section']))

        project = data.get('project_info') or {}
        comparative = data.get('comparative') or {}
        project_domain = project.get('domain', '')
        competitors = project.get('selected_competitors') or []

        if not competitors:
            elements.append(Paragraph(
                "No competitors configured for this project. "
                "Add competitors in project settings to enable comparative analysis.",
                styles['no_data']
            ))
            return

        elements.append(Paragraph(
            f"Comparing <b>{ManualAiPdfExportService._escape_html(project_domain)}</b> "
            f"against {len(competitors)} selected competitor(s) over the analyzed period.",
            styles['body']
        ))
        elements.append(Spacer(1, 0.4 * cm))

        # ── Chart 1: Visibility % over time ──
        vis_chart_data = comparative.get('visibility_chart') or {}
        pos_chart_data = comparative.get('position_chart') or {}
        dates = vis_chart_data.get('dates') or []

        if dates and vis_chart_data.get('datasets'):
            elements.append(Paragraph("Visibility % over time", styles['subsection']))
            chart = ManualAiPdfExportService._build_multiseries_linechart(
                dates, vis_chart_data.get('datasets', []),
                y_min=0, y_max=100, y_format='%d%%',
                styles=styles,
            )
            if chart is not None:
                elements.append(chart)
        else:
            elements.append(Paragraph(
                "Not enough data points to plot visibility over time.",
                styles['no_data']
            ))

        elements.append(Spacer(1, 0.4 * cm))

        # ── Chart 2: Average Position over time ──
        pos_dates = pos_chart_data.get('dates') or []
        if pos_dates and pos_chart_data.get('datasets'):
            elements.append(Paragraph("Average Position over time", styles['subsection']))

            # Compute y-axis max from the data (positions are typically 1-20)
            max_pos = 1
            for ds in pos_chart_data.get('datasets', []):
                for v in (ds.get('data') or []):
                    if v is not None:
                        try:
                            max_pos = max(max_pos, float(v))
                        except (TypeError, ValueError):
                            continue
            y_max = max(10, int(max_pos) + 2)

            chart = ManualAiPdfExportService._build_multiseries_linechart(
                pos_dates, pos_chart_data.get('datasets', []),
                y_min=0, y_max=y_max, y_format='#%d',
                styles=styles,
            )
            if chart is not None:
                elements.append(chart)
                elements.append(Paragraph(
                    "Lower is better — position #1 is the top of the AI Overview.",
                    styles['caption']
                ))

        elements.append(Spacer(1, 0.4 * cm))

        # ── Summary table: current visibility + avg position per entity ──
        summary_rows = [['Entity', 'Latest Visibility %', 'Latest Avg Position']]

        def _latest_value(series: list):
            """Find the last non-None value in a data series."""
            for v in reversed(series or []):
                if v is not None:
                    try:
                        return float(v)
                    except (TypeError, ValueError):
                        continue
            return None

        entities_seen = []
        for vs_ds in vis_chart_data.get('datasets', []):
            label = vs_ds.get('label', 'Unknown')
            entities_seen.append(label)
            latest_vis = _latest_value(vs_ds.get('data') or [])

            # Find matching position series
            latest_pos = None
            for ps_ds in pos_chart_data.get('datasets', []):
                if ps_ds.get('label') == label:
                    latest_pos = _latest_value(ps_ds.get('data') or [])
                    break

            vis_str = f"{latest_vis:.1f}%" if latest_vis is not None else 'N/A'
            pos_str = f"#{latest_pos:.1f}" if latest_pos is not None else 'N/A'

            summary_rows.append([
                ManualAiPdfExportService._truncate(label, 40),
                vis_str,
                pos_str,
            ])

        if len(summary_rows) > 1:
            s_table = Table(summary_rows, colWidths=[9 * cm, 4 * cm, 4 * cm])
            ss = ManualAiPdfExportService._base_table_style(len(summary_rows), styles)
            ss.append(('ALIGN', (0, 1), (0, -1), 'LEFT'))
            # Highlight project row in green
            if entities_seen and entities_seen[0] == project_domain:
                ss.append(('BACKGROUND', (0, 1), (-1, 1), styles['CLR_GREEN_CELL']))
                ss.append(('FONTNAME', (0, 1), (-1, 1), 'Helvetica-Bold'))
            s_table.setStyle(TableStyle(ss))
            elements.append(s_table)

    @staticmethod
    def _build_multiseries_linechart(
        dates: List[str], datasets: List[Dict],
        y_min: float, y_max: float, y_format: str,
        styles: Dict,
    ):
        """
        Build a multi-series LinePlot from UI-shaped chart data.

        Each dataset: {label, data (list with possible None), borderColor}
        Filters None values per series independently (LinePlot doesn't handle None).
        Draws a legend at the bottom.
        """
        from reportlab.graphics.charts.lineplots import LinePlot
        from reportlab.graphics.shapes import Drawing, Rect, String
        from reportlab.graphics.widgets.markers import makeMarker
        from reportlab.lib import colors
        from reportlab.lib.units import cm

        if not dates or not datasets:
            return None

        chart_w = 17 * cm
        chart_h = 6.5 * cm
        drawing = Drawing(float(chart_w), float(chart_h))
        drawing.add(Rect(
            0, 0, float(chart_w), float(chart_h),
            fillColor=colors.HexColor('#FAFAFA'), strokeColor=None,
        ))

        # Build plot_data filtering None values per series. Each series can
        # have a different number of points — LinePlot accepts that.
        plot_data = []
        series_colors = []
        series_labels = []
        has_any_data = False

        for ds in datasets:
            values = ds.get('data') or []
            points = [
                (i, float(v))
                for i, v in enumerate(values)
                if v is not None
            ]
            if len(points) < 1:
                # Skip fully empty series — LinePlot breaks on empty lists
                continue
            plot_data.append(points)
            series_colors.append(ds.get('borderColor', '#6B7280'))
            series_labels.append(ds.get('label', 'Unknown'))
            has_any_data = True

        if not has_any_data:
            return None

        lp = LinePlot()
        lp.x = 40
        lp.y = 45
        lp.width = float(chart_w) - 60
        lp.height = float(chart_h) - 75
        lp.data = plot_data

        for si, color_hex in enumerate(series_colors):
            try:
                lp.lines[si].strokeColor = colors.HexColor(color_hex)
            except Exception:
                lp.lines[si].strokeColor = colors.HexColor('#6B7280')
            lp.lines[si].strokeWidth = 2.5 if si == 0 else 1.8
            lp.lines[si].symbol = makeMarker('Circle')
            lp.lines[si].symbol.size = 4 if si == 0 else 3

        n = len(dates)
        tick_step = max(1, n // 8)
        _dates_ref = dates

        lp.xValueAxis.valueMin = 0
        lp.xValueAxis.valueMax = max(n - 1, 1)
        lp.xValueAxis.valueSteps = list(range(0, n, tick_step))
        lp.xValueAxis.labelTextFormat = (
            lambda v, _d=_dates_ref:
            _d[int(v)][-5:] if 0 <= int(v) < len(_d) else ''
        )
        lp.xValueAxis.labels.fontSize = 7
        lp.xValueAxis.labels.angle = 0
        lp.xValueAxis.strokeColor = colors.HexColor('#E5E7EB')

        lp.yValueAxis.valueMin = y_min
        lp.yValueAxis.valueMax = y_max
        if y_max - y_min > 0:
            lp.yValueAxis.valueStep = (y_max - y_min) / 5
        lp.yValueAxis.labelTextFormat = y_format
        lp.yValueAxis.labels.fontSize = 7
        lp.yValueAxis.strokeColor = colors.HexColor('#E5E7EB')
        lp.yValueAxis.gridStrokeColor = colors.HexColor('#F3F4F6')
        lp.yValueAxis.visibleGrid = 1

        drawing.add(lp)

        # Legend at bottom
        legend_x = 40
        legend_y = 12
        for si, label in enumerate(series_labels):
            try:
                c = colors.HexColor(series_colors[si])
            except Exception:
                c = colors.HexColor('#6B7280')
            drawing.add(Rect(legend_x, legend_y, 8, 8, fillColor=c, strokeColor=None))
            display_label = ManualAiPdfExportService._truncate(label, 22).upper()
            drawing.add(String(
                legend_x + 11, legend_y + 1, display_label,
                fontSize=6, fillColor=colors.HexColor(_CLR_LIGHT_GRAY)
            ))
            legend_x += len(display_label) * 3.8 + 22
            if legend_x > float(chart_w) - 50:
                # Break to a second line if too many series
                legend_x = 40
                legend_y -= 10

        return drawing

    # ═══════════════════════════════════════════════════════════════════════
    #  Page 6 — AI Overview Keywords Details
    # ═══════════════════════════════════════════════════════════════════════

    @staticmethod
    def _build_page6_keywords(elements: list, data: Dict, styles: Dict):
        from reportlab.lib.units import cm
        from reportlab.platypus import PageBreak, Paragraph, Spacer, Table, TableStyle

        elements.append(PageBreak())
        elements.append(Spacer(1, 0.3 * cm))
        elements.append(Paragraph("AI Overview Keywords Details", styles['section']))

        keywords_latest = data.get('keywords_latest') or {}
        kw_results = keywords_latest.get('keywordResults') or []
        all_competitors = keywords_latest.get('competitorDomains') or []
        total_kw = int(keywords_latest.get('total_keywords') or len(kw_results))

        if not kw_results:
            elements.append(Paragraph(
                "No AI Overview keyword data available. Run an analysis to populate this section.",
                styles['no_data']
            ))
            return

        # Pick top 3 competitors by "times present in keywordResults"
        comp_hit_count = {c: 0 for c in all_competitors}
        for kw in kw_results:
            for comp in (kw.get('competitors') or []):
                d = comp.get('domain')
                if d in comp_hit_count and comp.get('position') is not None:
                    comp_hit_count[d] += 1

        top_competitors = sorted(
            comp_hit_count.keys(),
            key=lambda d: comp_hit_count[d],
            reverse=True,
        )[:3]
        extra_competitors = len(all_competitors) - len(top_competitors)

        # Header row
        header = ['Keyword', 'You (pos)']
        for comp in top_competitors:
            header.append(
                ManualAiPdfExportService._truncate(comp, 14) + '\n(pos)'
            )

        # Build data rows (top 30)
        display_rows = []
        for kw in kw_results[:30]:
            kw_text = kw.get('keyword', '')
            user_in_aio = kw.get('user_domain_in_aio')
            user_pos = kw.get('user_domain_position')

            if not user_in_aio:
                user_cell = '—'
                user_row_meta = 'absent'
            elif user_pos is None:
                user_cell = 'mentioned'
                user_row_meta = 'mentioned_no_pos'
            else:
                user_cell = f'#{int(user_pos)}'
                if user_pos <= 3:
                    user_row_meta = 'top3'
                elif user_pos <= 10:
                    user_row_meta = 'top10'
                else:
                    user_row_meta = 'beyond10'

            row = [
                Paragraph(
                    ManualAiPdfExportService._escape_html(ManualAiPdfExportService._truncate(kw_text, 50)),
                    styles['body_small'],
                ),
                user_cell,
            ]

            # Build dict of competitor positions for this keyword
            comp_positions = {
                (c.get('domain') or ''): c.get('position')
                for c in (kw.get('competitors') or [])
            }

            for comp_domain in top_competitors:
                pos = comp_positions.get(comp_domain)
                if pos is None:
                    row.append('—')
                else:
                    row.append(f'#{int(pos)}')

            display_rows.append((row, user_row_meta, user_pos))

        # Build the table
        num_comp_cols = len(top_competitors)
        num_cols = 2 + num_comp_cols

        # Column widths
        kw_width = 7 * cm
        you_width = 1.8 * cm
        remaining = 17 - 7 - 1.8
        if num_comp_cols > 0:
            comp_width = (remaining / num_comp_cols) * cm
        else:
            kw_width = 13 * cm  # Extend keyword column if no competitors
            comp_width = 0

        col_widths = [kw_width, you_width]
        for _ in range(num_comp_cols):
            col_widths.append(comp_width)

        table_rows = [header] + [r for r, _, _ in display_rows]
        kw_table = Table(table_rows, colWidths=col_widths, repeatRows=1)
        ks = ManualAiPdfExportService._base_table_style(len(table_rows), styles)
        ks.append(('ALIGN', (0, 1), (0, -1), 'LEFT'))
        ks.append(('VALIGN', (0, 0), (-1, -1), 'MIDDLE'))
        ks.append(('FONTSIZE', (0, 1), (-1, -1), 7))

        # Color the "You (pos)" column cell based on position
        for i, (_, meta, pos_val) in enumerate(display_rows):
            r = i + 1
            if meta == 'top3':
                ks.append(('BACKGROUND', (1, r), (1, r), styles['CLR_GREEN_CELL']))
            elif meta == 'top10':
                ks.append(('BACKGROUND', (1, r), (1, r), styles['CLR_YELLOW_CELL']))
            elif meta == 'beyond10':
                ks.append(('BACKGROUND', (1, r), (1, r), styles['CLR_BLUE_CELL']))
            elif meta == 'mentioned_no_pos':
                ks.append(('BACKGROUND', (1, r), (1, r), styles['CLR_YELLOW_CELL']))
            else:  # absent
                ks.append(('BACKGROUND', (1, r), (1, r), styles['CLR_RED_CELL']))

        kw_table.setStyle(TableStyle(ks))
        elements.append(kw_table)

        elements.append(Spacer(1, 0.3 * cm))

        # Footer with context
        footer_notes = []
        if total_kw > 30:
            footer_notes.append(f"Showing top 30 of {total_kw} keywords with AI Overview")
        if extra_competitors > 0:
            footer_notes.append(f"+{extra_competitors} more competitor(s) not shown — see Excel export for the full breakdown")
        footer_notes.append("Sort order: your mentions first, then by best position, then alphabetical.")
        footer_notes.append("Color code: green = top 3, yellow = top 10, blue = beyond 10, red = not mentioned.")

        elements.append(Paragraph(' · '.join(footer_notes), styles['caption']))

    # ═══════════════════════════════════════════════════════════════════════
    #  Page 7 — Top Mentioned URLs in AI Overview
    # ═══════════════════════════════════════════════════════════════════════

    @staticmethod
    def _build_page7_top_urls(elements: list, data: Dict, styles: Dict):
        from reportlab.lib.units import cm
        from reportlab.platypus import PageBreak, Paragraph, Spacer, Table, TableStyle

        elements.append(PageBreak())
        elements.append(Spacer(1, 0.3 * cm))
        elements.append(Paragraph("Top Mentioned URLs in AI Overview", styles['section']))
        elements.append(Paragraph(
            "Ranking of the URLs most frequently cited by Google's AI Overview for the keywords tracked in this project.",
            styles['body']
        ))
        elements.append(Spacer(1, 0.3 * cm))

        top_urls = data.get('top_urls') or []
        project = data.get('project_info') or {}
        project_domain = (project.get('domain') or '').lower().strip()

        if not top_urls:
            elements.append(Paragraph(
                "No cited URL data available for this period.",
                styles['no_data']
            ))
            return

        header = ['Rank', 'URL', 'Mentions', '% of Total', 'Avg Position']
        url_rows = [header]
        is_brand_row = [False]

        for u in top_urls[:20]:
            raw_url = u.get('url', '') or ''
            display_url = ManualAiPdfExportService._truncate(raw_url, 58)

            if raw_url.startswith('http'):
                url_para = Paragraph(
                    f'<a href="{ManualAiPdfExportService._escape_html(raw_url)}" color="#2563EB">{ManualAiPdfExportService._escape_html(display_url)}</a>',
                    styles['url_link'],
                )
            else:
                url_para = Paragraph(
                    ManualAiPdfExportService._escape_html(display_url),
                    styles['body_small'],
                )

            avg_pos = u.get('avg_position')
            avg_pos_str = f"#{float(avg_pos):.1f}" if avg_pos else 'N/A'

            url_rows.append([
                str(u.get('rank', '')),
                url_para,
                str(u.get('mentions', 0)),
                f"{float(u.get('percentage', 0)):.1f}%",
                avg_pos_str,
            ])

            is_brand = bool(project_domain) and project_domain in raw_url.lower()
            is_brand_row.append(is_brand)

        widths = [1.2 * cm, 9.5 * cm, 1.8 * cm, 2 * cm, 2.5 * cm]
        u_table = Table(url_rows, colWidths=widths, repeatRows=1)
        us = ManualAiPdfExportService._base_table_style(len(url_rows), styles)
        us.append(('ALIGN', (1, 1), (1, -1), 'LEFT'))
        us.append(('VALIGN', (0, 0), (-1, -1), 'MIDDLE'))

        # Highlight brand URL rows
        for i, is_brand in enumerate(is_brand_row):
            if is_brand:
                us.append(('BACKGROUND', (0, i), (-1, i), styles['CLR_GREEN_CELL']))

        u_table.setStyle(TableStyle(us))
        elements.append(u_table)

        elements.append(Spacer(1, 0.3 * cm))
        elements.append(Paragraph(
            f"Showing top {min(20, len(top_urls))} URLs by total mentions. "
            f"Rows highlighted in green belong to your domain.",
            styles['caption']
        ))

    # ═══════════════════════════════════════════════════════════════════════
    #  Page 8 — Global AI Overview Domains Ranking
    # ═══════════════════════════════════════════════════════════════════════

    @staticmethod
    def _build_page8_domains_ranking(elements: list, data: Dict, styles: Dict):
        from reportlab.lib.units import cm
        from reportlab.platypus import PageBreak, Paragraph, Spacer, Table, TableStyle

        elements.append(PageBreak())
        elements.append(Spacer(1, 0.3 * cm))
        elements.append(Paragraph("Global AI Overview Domains Ranking", styles['section']))
        elements.append(Paragraph(
            "All domains detected in the AI Overview for the keywords tracked in this project. "
            "Your domain and selected competitors are highlighted.",
            styles['body']
        ))
        elements.append(Spacer(1, 0.3 * cm))

        domains = data.get('global_domains') or []

        if not domains:
            elements.append(Paragraph(
                "No global domain data available for this period.",
                styles['no_data']
            ))
            return

        header = ['Rank', 'Domain', 'Appearances', 'Avg Position', 'Visibility %']
        d_rows = [header]
        row_types = [None]  # first row is header

        for d in domains[:20]:
            rank = d.get('rank', '')
            dom = d.get('detected_domain', '')
            app = d.get('appearances', 0)
            avg_pos = d.get('avg_position')
            vis = d.get('visibility_percentage', 0)

            avg_pos_str = f"#{float(avg_pos):.1f}" if avg_pos else 'N/A'

            d_rows.append([
                str(rank),
                ManualAiPdfExportService._truncate(dom, 40),
                str(app),
                avg_pos_str,
                f"{float(vis):.1f}%",
            ])
            row_types.append(d.get('domain_type', 'other'))

        widths = [1.5 * cm, 8 * cm, 2.3 * cm, 2.5 * cm, 2.7 * cm]
        d_table = Table(d_rows, colWidths=widths, repeatRows=1)
        ds = ManualAiPdfExportService._base_table_style(len(d_rows), styles)
        ds.append(('ALIGN', (1, 1), (1, -1), 'LEFT'))

        for i, row_type in enumerate(row_types):
            if row_type == 'project':
                ds.append(('BACKGROUND', (0, i), (-1, i), styles['CLR_GREEN_CELL']))
                ds.append(('FONTNAME', (0, i), (-1, i), 'Helvetica-Bold'))
            elif row_type == 'competitor':
                ds.append(('BACKGROUND', (0, i), (-1, i), styles['CLR_YELLOW_CELL']))

        d_table.setStyle(TableStyle(ds))
        elements.append(d_table)

        elements.append(Spacer(1, 0.3 * cm))
        elements.append(Paragraph(
            f"Showing top {min(20, len(domains))} domains by total appearances. "
            f"Green = your domain, yellow = selected competitors.",
            styles['caption']
        ))

    # ═══════════════════════════════════════════════════════════════════════
    #  Page 9 — AI Overview vs Organic Comparison
    # ═══════════════════════════════════════════════════════════════════════

    @staticmethod
    def _build_page9_aio_vs_organic(elements: list, data: Dict, styles: Dict):
        from reportlab.graphics.charts.barcharts import HorizontalBarChart
        from reportlab.graphics.shapes import Drawing, Rect, String
        from reportlab.lib import colors
        from reportlab.lib.units import cm
        from reportlab.platypus import PageBreak, Paragraph, Spacer, Table, TableStyle

        elements.append(PageBreak())
        elements.append(Spacer(1, 0.3 * cm))
        elements.append(Paragraph("AI Overview vs Organic Results", styles['section']))
        elements.append(Paragraph(
            "Is your organic visibility translating into AI Overview citations?",
            styles['body']
        ))
        elements.append(Spacer(1, 0.3 * cm))

        aio_vs = data.get('aio_vs_organic') or {}
        overall = aio_vs.get('overall') or {}
        my_stats = aio_vs.get('my_domain_stats') or {}
        position_corr = aio_vs.get('position_correlation') or {}
        per_keyword = aio_vs.get('per_keyword') or []

        total_kw = int(overall.get('total_keywords_analyzed') or 0)

        if total_kw == 0:
            elements.append(Paragraph(
                "No comparison data available for this period — this feature requires keywords that have "
                "both an AI Overview and organic results in the same analysis. Run an analysis to populate this section.",
                styles['no_data']
            ))
            return

        # ── Block A: Overall stats bar ──
        project_domain_str = my_stats.get('project_domain', 'N/A') or 'N/A'
        overlap_url = overall.get('overlap_rate_url', 0)
        overlap_dom = overall.get('overlap_rate_domain', 0)

        stats_rows = [[
            Paragraph(f"<b>{total_kw}</b>", styles['kpi_value']),
            Paragraph(f"<b>{overlap_url}%</b>", styles['kpi_value']),
            Paragraph(f"<b>{overlap_dom}%</b>", styles['kpi_value']),
            Paragraph(
                f"<b>{ManualAiPdfExportService._escape_html(ManualAiPdfExportService._truncate(project_domain_str, 28))}</b>",
                styles['kpi_value'],
            ),
        ], [
            Paragraph("Keywords analyzed", styles['kpi_label']),
            Paragraph("URL-exact overlap", styles['kpi_label']),
            Paragraph("Domain overlap", styles['kpi_label']),
            Paragraph("Your domain", styles['kpi_label']),
        ]]

        col_w = 4.25 * cm
        stats_table = Table(
            stats_rows,
            colWidths=[col_w, col_w, col_w, col_w],
            rowHeights=[1.1 * cm, 0.55 * cm],
        )
        stats_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('BACKGROUND', (0, 0), (-1, -1), styles['CLR_SUBHEADER']),
            ('BOX', (0, 0), (-1, -1), 1, styles['CLR_BORDER']),
            ('LINEAFTER', (0, 0), (-2, -1), 0.5, styles['CLR_BORDER']),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        elements.append(stats_table)
        elements.append(Spacer(1, 0.5 * cm))

        # ── Block B: 4 quadrant KPI cards ──
        elements.append(Paragraph("Your domain — 4 quadrants", styles['subsection']))

        both = int(my_stats.get('keywords_in_both') or 0)
        org_only = int(my_stats.get('keywords_organic_only') or 0)
        aio_only = int(my_stats.get('keywords_aio_only') or 0)
        neither = int(my_stats.get('keywords_neither') or 0)

        q_rows = [
            [
                Paragraph(f"<b>{both}</b>", styles['kpi_value']),
                Paragraph(f"<b>{org_only}</b>", styles['kpi_value']),
                Paragraph(f"<b>{aio_only}</b>", styles['kpi_value']),
                Paragraph(f"<b>{neither}</b>", styles['kpi_value']),
            ],
            [
                Paragraph("Rank &amp; Cited", styles['kpi_label']),
                Paragraph("Rank, Not Cited<br/><font size='6' color='#6b7280'>GEO opportunity</font>", styles['kpi_label']),
                Paragraph("Cited, Not Ranking<br/><font size='6' color='#6b7280'>SEO opportunity</font>", styles['kpi_label']),
                Paragraph("Neither", styles['kpi_label']),
            ],
        ]

        q_w = 4.25 * cm
        q_table = Table(
            q_rows,
            colWidths=[q_w, q_w, q_w, q_w],
            rowHeights=[1.0 * cm, 0.8 * cm],
        )
        q_style_cmds = [
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('BOX', (0, 0), (0, -1), 1, styles['CLR_BORDER']),
            ('BOX', (1, 0), (1, -1), 1, styles['CLR_BORDER']),
            ('BOX', (2, 0), (2, -1), 1, styles['CLR_BORDER']),
            ('BOX', (3, 0), (3, -1), 1, styles['CLR_BORDER']),
            ('BACKGROUND', (0, 0), (0, -1), styles['CLR_GREEN_CELL']),
            ('BACKGROUND', (1, 0), (1, -1), styles['CLR_YELLOW_CELL']),
            ('BACKGROUND', (2, 0), (2, -1), styles['CLR_BLUE_CELL']),
            ('BACKGROUND', (3, 0), (3, -1), styles['CLR_GRAY_CELL']),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]
        q_table.setStyle(TableStyle(q_style_cmds))
        elements.append(q_table)
        elements.append(Spacer(1, 0.4 * cm))

        # ── Block C: Position Correlation horizontal bars ──
        elements.append(Paragraph(
            "Does ranking higher boost AI Overview visibility?",
            styles['subsection']
        ))

        buckets_def = [
            ('top_3', 'Ranks in Top 3'),
            ('positions_4_10', 'Ranks in Positions 4-10'),
            ('beyond_top_10', 'Ranks in Positions 11+'),
            ('not_ranking', "Doesn't rank organically"),
        ]

        # Drop empty buckets (common for beyond_top_10)
        active_buckets = []
        for key, label in buckets_def:
            bucket = position_corr.get(key) or {}
            total_b = int(bucket.get('total_keywords') or 0)
            cited = int(bucket.get('cited_in_aio') or 0)
            rate = float(bucket.get('aio_rate') or 0)
            if total_b > 0:
                active_buckets.append((key, label, total_b, cited, rate))

        if active_buckets:
            pc_rows = [['Bucket', 'Cited / Total', 'AIO rate', 'Visualization']]
            pc_bar_values = []

            for key, label, total_b, cited, rate in active_buckets:
                # Build a tiny bar using unicode blocks
                bar_len = int(round(rate / 5))  # 20 units max
                bar_str = '█' * bar_len + '░' * (20 - bar_len)
                pc_rows.append([
                    label,
                    f"{cited} / {total_b}",
                    f"{rate:.1f}%",
                    bar_str,
                ])
                pc_bar_values.append((key, rate))

            pc_widths = [5 * cm, 3 * cm, 2.5 * cm, 6.5 * cm]
            pc_table = Table(pc_rows, colWidths=pc_widths)
            pcs = ManualAiPdfExportService._base_table_style(len(pc_rows), styles)
            pcs.append(('ALIGN', (0, 1), (0, -1), 'LEFT'))
            pcs.append(('ALIGN', (3, 1), (3, -1), 'LEFT'))
            pcs.append(('FONTNAME', (3, 1), (3, -1), 'Courier'))
            pcs.append(('FONTSIZE', (3, 1), (3, -1), 8))

            # Color the left border/cell per bucket
            bucket_colors_map = {
                'top_3': styles['CLR_GREEN_CELL'],
                'positions_4_10': styles['CLR_BLUE_CELL'],
                'beyond_top_10': styles['CLR_YELLOW_CELL'],
                'not_ranking': styles['CLR_GRAY_CELL'],
            }
            for i, (key, _rate) in enumerate(pc_bar_values):
                r = i + 1
                pcs.append(('BACKGROUND', (0, r), (0, r), bucket_colors_map.get(key, styles['CLR_GRAY_CELL'])))

            pc_table.setStyle(TableStyle(pcs))
            elements.append(pc_table)

            elements.append(Spacer(1, 0.2 * cm))
            elements.append(Paragraph(
                "Each bar = share of keywords in that organic bucket that are also cited in the AI Overview. "
                "Higher bars on Top 3 = strong correlation between organic ranking and AI Overview visibility.",
                styles['caption']
            ))
        else:
            elements.append(Paragraph(
                "No position correlation data available for this period.",
                styles['no_data']
            ))

        elements.append(Spacer(1, 0.5 * cm))

        # ── Block D: Per-keyword breakdown (top 20) ──
        elements.append(Paragraph("Per-keyword breakdown (top 20)", styles['subsection']))

        if per_keyword:
            quadrant_labels = {
                'both': 'Rank & Cited',
                'organic_only': 'Rank only',
                'aio_only': 'Cited only',
                'neither': 'Neither',
            }

            kw_header = ['#', 'Keyword', 'Org. pos', 'AIO refs', 'Overlap', 'Quadrant']
            kw_rows = [kw_header]
            kw_quadrants = [None]

            for idx, kw in enumerate(per_keyword[:20], start=1):
                kw_text = kw.get('keyword', '')
                org_pos = kw.get('my_organic_position')
                aio_refs = int(kw.get('aio_refs_count') or 0)
                overlap_url_c = int(kw.get('overlap_url_count') or 0)
                overlap_dom_c = int(kw.get('overlap_domain_count') or 0)
                quadrant = kw.get('quadrant', 'neither')

                pos_str = f'#{org_pos}' if org_pos else '—'
                overlap_str = f"{overlap_url_c} / {overlap_dom_c}"

                kw_rows.append([
                    str(idx),
                    Paragraph(
                        ManualAiPdfExportService._escape_html(
                            ManualAiPdfExportService._truncate(kw_text, 45)
                        ),
                        styles['body_small'],
                    ),
                    pos_str,
                    str(aio_refs),
                    overlap_str,
                    quadrant_labels.get(quadrant, quadrant),
                ])
                kw_quadrants.append(quadrant)

            kw_widths = [1 * cm, 7 * cm, 1.8 * cm, 1.8 * cm, 2 * cm, 3.4 * cm]
            kw_t = Table(kw_rows, colWidths=kw_widths, repeatRows=1)
            kws = ManualAiPdfExportService._base_table_style(len(kw_rows), styles)
            kws.append(('ALIGN', (1, 1), (1, -1), 'LEFT'))
            kws.append(('FONTSIZE', (0, 1), (-1, -1), 7))

            quadrant_bg = {
                'both': styles['CLR_GREEN_CELL'],
                'organic_only': styles['CLR_YELLOW_CELL'],
                'aio_only': styles['CLR_BLUE_CELL'],
                'neither': styles['CLR_GRAY_CELL'],
            }
            for i, q in enumerate(kw_quadrants):
                if q and q in quadrant_bg:
                    kws.append(('BACKGROUND', (5, i), (5, i), quadrant_bg[q]))

            kw_t.setStyle(TableStyle(kws))
            elements.append(kw_t)
        else:
            elements.append(Paragraph(
                "No per-keyword data available.",
                styles['no_data']
            ))
