# 1) Instala dependencias nativas de Chromium  
# 2) Descarga el binario de Chromium
# La inicialización de BD se hace ahora en el startup de la app
release: python3 -m playwright install-deps && python3 -m playwright install chromium
web:     python3 app.py
