# -*- coding: utf-8 -*-
"""Orquestador del scanner: recoge evidencias de un dominio y ejecuta los checks.

Portable y sin estado global salvo un LOG_SINK opcional para progreso en vivo.
El check 6.3 (agentes reales) NO se ejecuta aquí: requiere browser-use, que
choca con las dependencias fijadas de la app. En servidor queda como manual;
en local se inyecta vía ctx["agent_tests"] desde la herramienta standalone.
"""
import json
import re
from urllib.parse import urlparse

from . import checks as checks_mod
from . import discovery, scoring
from .config import WELLKNOWN_PATHS, UA_HUMAN, BOT_UAS, get_key
from .httpfetch import (bot_access_matrix, fetch, jina_read, rapid_fire,
                        status_only, assert_public_url, BlockedURLError)
from .render import render as render_page

LOG_SINK = None


def _log(msg):
    if LOG_SINK is not None:
        LOG_SINK.append(msg)


def probe_wellknown(base):
    """Sondea rutas agénticas validando CONTENIDO (evita soft-404 de los CMS).

    Devuelve (códigos, metadatos). Los metadatos permiten juzgar CALIDAD y no
    solo presencia: un llms.txt de 900 KB autogenerado no vale lo mismo que uno
    de 30 KB curado, y medir solo "existe" invierte el ranking real.
    """
    out, meta = {}, {}
    for p in WELLKNOWN_PATHS:
        res = fetch(base + p, timeout=12)
        code = res["status"]
        if code == 200:
            body = (res["body"] or "").strip()
            is_html = "<html" in body[:400].lower() or "<!doctype" in body[:200].lower()
            text_paths = ("/llms.txt", "/llms-full.txt", "/auth.md", "/.well-known/skills")
            if p in text_paths or p.endswith(".md"):
                valid = not is_html and len(body) > 20
            elif p.endswith(".json") or p in ("/mcp", "/ask") or p.startswith("/.well-known/"):
                try:
                    json.loads(body)
                    valid = True
                except (json.JSONDecodeError, ValueError):
                    valid = not is_html and any(k in body[:500]
                                                for k in ("jsonrpc", "mcp", "openapi"))
            elif p == "/api-docs":
                valid = "swagger" in body.lower()[:3000] or "openapi" in body.lower()[:3000]
            else:
                valid = not is_html
            out[p] = 200 if valid else 0
            if valid:
                meta[p] = {
                    "bytes": len(body),
                    "lineas": body.count("\n") + 1,
                    "enlaces": body.count("](http") + body.count("- http"),
                    "autogenerado": bool(re.search(
                        r"(?i)(generado (por|con)|generated by|auto-?generated|"
                        r"all in one seo|yoast|rank ?math|plugin)", body[:600])),
                }
        else:
            out[p] = code
    return out, meta


def probe_error_handling(base):
    """Sonda de estados de error: pide una URL que no puede existir.

    Un soft-404 (HTTP 200 en una página inexistente) es un fallo agéntico grave:
    el agente cree que la operación fue bien y sigue con datos inventados. Un
    humano lee "no encontrado"; el agente solo mira el código de estado.
    """
    probe = base + "/agent-readiness-probe-404-no-existe-xyz"
    res = fetch(probe, timeout=15, ua=UA_HUMAN)
    body = res["body"] or ""
    text = re.sub(r"(?is)<(script|style).*?</\1>|<[^>]+>", " ", body)
    looks_missing = bool(re.search(
        r"(?i)no (se ha |hemos )?(encontrado|existe)|not found|404|"
        r"página no disponible|pagina no encontrada|error 404", text[:4000]))
    # ¿ofrece salida? (buscador o navegación para que el agente se recupere)
    has_recovery = bool(re.search(r'(?i)<input[^>]+type=["\']search|role=["\']search|'
                                  r'<nav\b|<form[^>]+(search|buscar)', body))
    return {"status": res["status"], "looks_missing": looks_missing,
            "has_recovery": has_recovery, "url": probe}


LOGIN_URL_RE = re.compile(
    r'href=["\']([^"\']*/(login|signin|sign-in|iniciar-sesion|acceso|'
    r'mi-cuenta|my-account|account)[^"\']*)["\']', re.I)


def _es_ficha_producto(valid_blocks):
    """¿Esta página es una FICHA de producto, o un artículo que lo menciona?

    La prensa incrusta Product schema en piezas de afiliación ("los mejores
    ventiladores"): eldiario.es acababa clasificado como e-commerce por dos
    noticias en catalán. Dos exigencias para aceptarla como ficha:
      1. el Product debe ser vendible (offers con precio), no una mención;
      2. la página no debe declararse a la vez como artículo — si lleva
         NewsArticle/Article/BlogPosting, es contenido editorial.
    """
    if checks_mod.find_nodes(valid_blocks, "NewsArticle") \
            or checks_mod.find_nodes(valid_blocks, "Article") \
            or checks_mod.find_nodes(valid_blocks, "BlogPosting") \
            or checks_mod.find_nodes(valid_blocks, "LiveBlogPosting"):
        return False
    for prod in checks_mod.find_nodes(valid_blocks, "Product"):
        offers = prod.get("offers") or {}
        if isinstance(offers, list):
            offers = offers[0] if offers else {}
        if isinstance(offers, dict) and (offers.get("price")
                                         or offers.get("priceCurrency")
                                         or offers.get("lowPrice")):
            return True
    return False


def _trail_tipologia(ctx, typology_override):
    """Deja en el trail cómo se ha clasificado el sitio, y por qué.

    Vive fuera de gather_context para poder probarse sin red: el matiz que
    distingue "no hay señales" de "no hemos podido mirar" es justo el que se
    coló en producción (ver test_sin_senales_no_culpa_al_acceso).
    """
    def T(status, detail):
        ctx["trail"].append({"step": "detección de tipología", "status": status,
                             "detail": str(detail)[:300]})

    if typology_override:
        T("ok", f"{ctx['typology']} (forzada por configuración)")
        return

    typ_ev = ctx.get("typology_evidence") or {}
    pts_e = (typ_ev.get("ecommerce") or {}).get("puntos", 0)
    pts_s = (typ_ev.get("saas") or {}).get("puntos", 0)
    det = (f"{ctx['typology']} — e-commerce {pts_e} pts "
           f"{(typ_ev.get('ecommerce') or {}).get('fuertes')}, saas {pts_s} pts "
           f"{(typ_ev.get('saas') or {}).get('fuertes')}")
    if pts_e or pts_s:
        T("ok", det)
        return

    # "Cero señales" tenía UNA sola lectura ("el sitio nos bloquea") y se
    # afirmaba siempre. Caso real (batería 6): dnb.no nos sirvió 1,17 MB de
    # portada por HTTP 200 y aun así el informe decía "la web devuelve
    # poco/ningún contenido a accesos automatizados". Igual en rijksoverheid.nl
    # (318 KB), vg.no (431 KB), uu.nl y greenpeace.nl. Un banco, un ministerio,
    # una universidad, un periódico y una ONG no tienen señales de tienda ni de
    # SaaS porque NO son eso: la ausencia es correcta y el diagnóstico, falso.
    # Solo se culpa al acceso cuando de verdad no hemos podido leer la portada.
    home = ctx.get("home") or {}
    hb = home.get("body") or ""
    portada_vista = (len(hb) >= 500 and (home.get("status") == 200
                                         or home.get("_via") in ("render", "jina")))
    if portada_vista:
        T("ok", det + " — sin señales de e-commerce ni de SaaS en una portada que "
                      f"sí se leyó ({len(hb)} bytes): se clasifica como 'corporativo', "
                      "que es lo normal en banca, sector público, medios y ONG. "
                      "Si no lo es, fuerza la tipología en el formulario.")
    else:
        T("warn", det + " — SIN señales: la web devuelve poco/ningún contenido a "
                        "accesos automatizados. Se asume 'corporativo' por defecto; "
                        "si no lo es, fuerza la tipología en el formulario.")


def _abs_url(base, url):
    if url.startswith("//"):
        return "https:" + url
    if url.startswith("/"):
        return base + url
    if url.startswith("http"):
        return url
    return None


def probe_login(base, home_html, skip_render=False):
    """Localiza el área de acceso y la trae, para evaluar si un agente podría
    autenticarse (check 6.4). Si el sitio no tiene login, no es un fallo: es N/A.

    Prueba VARIOS candidatos (no solo el primer enlace) y, si el formulario no
    está en el HTML crudo, renderiza: hoy muchos logins se pintan con JS y
    quedarnos en el crudo daría un "no evaluable" que en realidad sí lo es.
    """
    host = urlparse(base).netloc.replace("www.", "")
    cands, seen = [], set()
    for m in LOGIN_URL_RE.finditer(home_html or ""):
        u = _abs_url(base, m.group(1))
        if not u or u in seen:
            continue
        if urlparse(u).netloc.replace("www.", "") != host:
            continue
        seen.add(u)
        cands.append(u)
        if len(cands) >= 4:
            break
    # rutas convencionales por si la home no enlaza el acceso
    cands += [base + p for p in ("/login", "/cuenta", "/mi-cuenta")
              if base + p not in seen]
    if not cands:
        return {"found": False}

    intentos, mejor = [], None
    for u in cands[:5]:
        res = fetch(u, timeout=20, ua=UA_HUMAN)
        body = res["body"] or ""
        has_pwd = bool(re.search(r'(?i)<input[^>]+type=["\']password', body))
        intentos.append({"url": u, "status": res["status"], "password_en_crudo": has_pwd})
        if res["status"] == 200 and has_pwd:
            return {"found": True, "url": u, "status": res["status"], "body": body,
                    "via": "http", "intentos": intentos}
        if res["status"] == 200 and mejor is None:
            mejor = {"url": u, "status": res["status"], "body": body}
    if mejor is None:
        return {"found": False, "intentos": intentos}
    # ningún candidato mostró el formulario en crudo: puede ser un login con JS
    if not skip_render:
        r = render_page(mejor["url"], timeout=60)
        if r.get("ok") and re.search(r'(?i)<input[^>]+type=["\']password', r.get("html") or ""):
            return {"found": True, "url": mejor["url"], "status": mejor["status"],
                    "body": r["html"], "via": "render", "intentos": intentos}
    return {"found": True, "url": mejor["url"], "status": mejor["status"],
            "body": mejor["body"], "via": "http", "intentos": intentos}


def probe_error_handling(base):
    """Sonda de estados de error: pide una URL que no puede existir.

    Un soft-404 (HTTP 200 en una página inexistente) es un fallo agéntico grave:
    el agente cree que la operación fue bien y sigue con datos inventados. Un
    humano lee "no encontrado"; el agente solo mira el código de estado.
    """
    probe = base + "/agent-readiness-probe-404-no-existe-xyz"
    res = fetch(probe, timeout=15, ua=UA_HUMAN)
    body = res["body"] or ""
    text = re.sub(r"(?is)<(script|style).*?</\1>|<[^>]+>", " ", body)
    looks_missing = bool(re.search(
        r"(?i)no (se ha |hemos )?(encontrado|existe)|not found|404|"
        r"página no disponible|pagina no encontrada|error 404", text[:4000]))
    # ¿ofrece salida? (buscador o navegación para que el agente se recupere)
    has_recovery = bool(re.search(r'(?i)<input[^>]+type=["\']search|role=["\']search|'
                                  r'<nav\b|<form[^>]+(search|buscar)', body))
    return {"status": res["status"], "looks_missing": looks_missing,
            "has_recovery": has_recovery, "url": probe}


def psi_cls(url):
    """CLS vía PageSpeed Insights (opcional). Requiere key para cuota decente."""
    api = ("https://www.googleapis.com/pagespeedonline/v5/runPagespeed"
           f"?url={url}&category=PERFORMANCE&strategy=mobile")
    key = get_key("pagespeed")
    if key:
        api += f"&key={key}"
    res = fetch(api, timeout=90, verify_public=False)
    if res["status"] != 200:
        return None
    try:
        data = json.loads(res["body"])
        return float(data["lighthouseResult"]["audits"]
                     ["cumulative-layout-shift"]["numericValue"])
    except (KeyError, ValueError, TypeError):
        return None


def gather_context(base, typology_override=None, skip_render=False, with_psi=False):
    """Pipeline de recogida. Cada etapa deja rastro en ctx['trail'] (fiabilidad)."""
    # `audit_domain` ya normaliza, pero a gather_context se le llama también
    # directamente (regresiones de tipología, herramientas sueltas) con el
    # dominio pelado. Sin esquema, urlparse deja netloc vacío, assert_public_url
    # falla con "esquema no permitido" y el error acababa traducido a
    # "cloudflare.com no resuelve en DNS. Verifica el dominio": mandábamos al
    # cliente a revisar un DNS impecable por un fallo de formato nuestro.
    # normalize() es idempotente, así que llamarla dos veces no molesta.
    base = discovery.normalize(base)
    ctx = {"base": base, "trail": []}

    def T(step, status, detail=""):
        ctx["trail"].append({"step": step, "status": status, "detail": str(detail)[:300]})

    _log("robots.txt…")
    ctx["robots"] = discovery.get_robots(base)
    rb = ctx["robots"]
    if rb["status"] == 0:
        T("robots.txt", "fail", "sin respuesta: checks 1.1-1.3 y 2.1 sin evidencia directa")
    else:
        T("robots.txt", "ok", f"HTTP {rb['status']}, {len(rb['raw'])} bytes"
          + (", devuelve HTML (hallazgo del sitio)" if rb["is_html"] else ""))

    _log("sitemap…")
    ctx["sitemap"] = discovery.get_sitemap_urls(base, ctx["robots"])
    ctx["sitemap_fresh"] = discovery.sitemap_freshness(ctx["sitemap"]["lastmods"])
    if ctx["sitemap"]["found"]:
        T("sitemap", "ok", f"{len(ctx['sitemap']['urls'])} URLs, {len(ctx['sitemap']['lastmods'])} lastmod")
    else:
        T("sitemap", "warn", "no localizado: muestreo limitado a la home (cobertura reducida)")

    _log("home…")
    ctx["home"] = fetch(base + "/", ua=UA_HUMAN)
    if ctx["home"]["status"] != 200 or len(ctx["home"]["body"]) < 500:
        if not skip_render:
            rendered = render_page(base + "/")
            if rendered.get("ok") and rendered.get("html"):
                ctx["home"]["body"] = rendered["html"]
                ctx["home"]["_via"] = "render"
        if len(ctx["home"].get("body", "")) < 500:
            jina = jina_read(base + "/")
            if jina:
                ctx["home"]["body"] = jina
                ctx["home"]["_via"] = "jina"
    via = ctx["home"].get("_via", "http")
    if len(ctx["home"].get("body", "")) < 500:
        T("home", "fail", "sin contenido por ninguna vía: checks de contenido sin evidencia")
    elif via != "http":
        T("home", "warn", f"obtenida vía {via} (acceso simple bloqueado/vacío): dato relevante")
    elif ctx["home"]["status"] != 200:
        # Un cuerpo grande con estado de error es la página del WAF, no la
        # portada. Decir "ok | HTTP 403" en el trail (mediamarkt.es, batería 5)
        # es justo lo que impide al analista ver que no vimos el sitio.
        T("home", "warn",
          f"HTTP {ctx['home']['status']} con {len(ctx['home']['body'])} bytes: "
          f"el cuerpo NO es la portada, es la respuesta de error/bloqueo del "
          f"servidor. Los checks de contenido no pueden apoyarse en él")
    else:
        T("home", "ok", f"HTTP {ctx['home']['status']}, {len(ctx['home']['body'])} bytes, TTFB {ctx['home']['ttfb']}s")

    _log("matriz de acceso de bots de IA…")
    ctx["bot_matrix"] = bot_access_matrix(base + "/")
    human = ctx["bot_matrix"].get("_human", 0)
    codes = ", ".join(f"{k}={v}" for k, v in ctx["bot_matrix"].items())
    T("matriz de acceso de bots", "ok" if human == 200 else "warn",
      codes + ("" if human == 200 else " — el UA humano no recibe 200: WAF puede distorsionar"))

    # RESCATE: si a nosotros nos cierran la puerta pero a un bot de IA no, la
    # web SÍ es legible para un agente y hay que leerla como él. Antes se
    # declaraba "no evaluable" mirando solo nuestro UA de navegador, ignorando
    # que la matriz de bots ya tenía la respuesta. Además es lo más fiel al
    # objeto de la auditoría: nos interesa lo que ve un bot de IA, no un Chrome.
    if len(ctx["home"].get("body", "")) < 500 or ctx["home"]["status"] != 200:
        for nombre, ua in BOT_UAS.items():
            if ctx["bot_matrix"].get(nombre) != 200:
                continue
            res = fetch(base + "/", ua=ua)
            if res["status"] == 200 and len(res["body"] or "") >= 500:
                ctx["home"] = res
                ctx["home"]["_via"] = f"bot:{nombre}"
                via = ctx["home"]["_via"]
                T("home (rescate)", "ok",
                  f"el acceso con UA de navegador no daba contenido, pero {nombre} "
                  f"recibe HTTP 200 con {len(res['body'])} bytes: se analiza lo que "
                  f"el sitio le sirve a un bot de IA, que es justo lo que auditamos")
                break

    if ctx["home"]["status"] == 0 and all(v == 0 for v in ctx["bot_matrix"].values()):
        # "No resuelve" y "resuelve pero nos deja colgados" NO son lo mismo.
        # Caso real (batería 5): fnac.fr resuelve perfectamente (165.160.13.20)
        # y su WAF descarta nuestras conexiones en silencio (ConnectTimeout).
        # Le decíamos al cliente "no responde (DNS/conexión). Verifica el
        # dominio", es decir, le mandábamos a revisar un DNS que está bien
        # mientras el hallazgo real era justo el contrario: el sitio es tan
        # hostil al acceso automatizado que un agente tampoco entraría.
        try:
            assert_public_url(base)
            resuelve = True
            motivo_bloqueo = ""
        except BlockedURLError as exc:
            resuelve = False
            # BlockedURLError NO significa solo "no resuelve": también cubre
            # esquema inválido y IP privada/reservada (guardarraíl SSRF).
            # Traducirlo todo a "no resuelve en DNS" manda al cliente a mirar
            # donde no es. Se conserva la causa real.
            motivo_bloqueo = str(exc)
        if resuelve:
            raise RuntimeError(
                f"{base} resuelve en DNS pero rechaza o deja sin respuesta TODAS "
                f"nuestras peticiones (humano y bots). El dominio no está mal "
                f"configurado: está bloqueando el acceso automatizado por completo. "
                f"Eso mismo le ocurriría a un agente, pero no podemos auditar lo que "
                f"no podemos ver: repite el análisis desde otra IP o con el sitio "
                f"en lista blanca.")
        raise RuntimeError(f"no se pudo acceder a {base}: {motivo_bloqueo}. "
                           f"Verifica el dominio.")

    _log("superficie agéntica (.well-known)…")
    ctx["wellknown"], ctx["wellknown_meta"] = probe_wellknown(base)
    hits = [p for p, c in ctx["wellknown"].items() if c == 200]
    T("superficie agéntica", "ok",
      f"{len(WELLKNOWN_PATHS)} rutas con validación de contenido; válidas: {', '.join(hits) or 'ninguna'}")

    all_urls = ctx["sitemap"]["urls"]
    if not all_urls:
        # sin sitemap no hay muestreo, y auditar solo la home deja ciegos los
        # checks de contenido (es.wikipedia.org, github.com). Los enlaces
        # internos de la portada son el plan B de cobertura.
        all_urls = discovery.harvest_links(base, ctx["home"]["body"])
        if all_urls:
            T("descubrimiento por enlaces", "ok",
              f"sin sitemap utilizable: {len(all_urls)} URLs internas extraídas "
              "de la portada para poder muestrear contenido real")
        else:
            # Ni sitemap ni UN SOLO enlace interno. Toda web real enlaza a algo:
            # esto significa que lo que nos han servido no es la portada, sino
            # una cáscara. Se marca aquí para que el guardarraíl lo recoja.
            ctx["cobertura_ciega"] = True
            T("descubrimiento por enlaces", "warn",
              "ni sitemap ni un solo enlace interno en lo que nos sirvieron como "
              "portada: no es una web sin enlaces, es que no estamos viendo la web")
    typ, typ_ev = discovery.detect_typology(ctx["home"]["body"], all_urls)
    ctx["typology"] = typology_override or typ
    ctx["typology_evidence"] = typ_ev
    _log(f"tipología: {ctx['typology']}")
    _trail_tipologia(ctx, typology_override)

    _log("muestreo de páginas…")
    buckets, sample = discovery.classify_and_sample(all_urls)
    ctx["buckets_size"] = {k: len(v) for k, v in buckets.items()}
    pages = []
    for item in sample:
        res = fetch(item["url"], ua=UA_HUMAN, timeout=20)
        if res["status"] != 200 or len(res["body"]) < 300:
            jina = jina_read(item["url"], timeout=60)
            if jina:
                res["body"] = jina
                res["status"] = res["status"] or 200
                res["_via"] = "jina"
        pages.append({"url": item["url"], "bucket": item["bucket"], "fetch": res})
    ctx["pages"] = pages
    ok_pages = sum(1 for p in pages if p["fetch"]["status"] == 200)
    via_fb = sum(1 for p in pages if p["fetch"].get("_via"))
    if not pages:
        T("muestreo de páginas", "warn", "0 páginas (sin sitemap): checks de contenido solo con la home")
    elif ok_pages < len(pages):
        T("muestreo de páginas", "warn",
          f"{ok_pages}/{len(pages)} accesibles ({via_fb} vía fallback); inaccesibles = hallazgo en 1.6")
    else:
        T("muestreo de páginas", "ok",
          f"{len(pages)} páginas de {len(all_urls)} URLs del sitemap ({via_fb} vía fallback)")
    # Promoción de fichas por CONTENIDO: muchas tiendas usan URLs propias
    # (pccomponentes.com/placa-base-..., hawkersco.com/gafas-...) que ningún
    # patrón de palabras clave reconoce. Si no hay bucket producto, se sondean
    # unas pocas URLs "otras" buscando Product schema — evidencia estructural
    # que además corrige la tipología si hacía falta.
    # Puerta: solo se sondea si hay ALGUNA señal textual de comercio. Sin ella,
    # un Product schema suelto no convierte el sitio en tienda: la prensa mete
    # Product en artículos de afiliación (eldiario.es salía "e-commerce" por
    # dos NOTICIAS promovidas como fichas).
    pts_ecom = (ctx.get("typology_evidence", {}).get("ecommerce") or {}).get("puntos", 0)
    if not any(p["bucket"] == "producto" and p["fetch"]["status"] == 200 for p in pages) \
            and len(buckets.get("otras", [])) >= 10 \
            and (ctx["typology"] == "ecommerce" or pts_ecom >= 1):
        _log("buscando fichas de producto por contenido…")
        # las fichas suelen tener el slug más largo y descriptivo del sitio
        candidatos = sorted(buckets["otras"],
                            key=lambda u: -urlparse(u).path.count("-"))[:5]
        promovidas, sondeos = 0, []
        for u in candidatos:
            res = fetch(u, ua=UA_HUMAN, timeout=15)
            sondeos.append(res["status"])
            # Se PARSEA el JSON-LD real, no se busca la cadena: la documentación
            # de stripe.com contiene '"@type": "Product"' como ejemplo de código
            # y el match de texto la convertía en tienda. Un bloque ld+json que
            # parsea y contiene un nodo Product sí es una ficha; un trozo de
            # texto que se le parece, no.
            if res["status"] == 200:
                valid_blocks, _inv = checks_mod.jsonld_blocks(res["body"] or "")
                if _es_ficha_producto(valid_blocks):
                    pages.append({"url": u, "bucket": "producto", "fetch": res})
                    promovidas += 1
            if promovidas >= 2:
                break
        if promovidas:
            T("fichas de producto por contenido", "ok",
              f"{promovidas} página(s) con Product schema encontradas fuera de los "
              f"patrones de URL: promovidas al bucket producto")
            # el cambio de tipología exige 2 fichas (una sola puede ser un
            # artículo de afiliación con Product schema); con 1, se promueve
            # la página para los checks pero la tipología no se toca
            if promovidas >= 2 and ctx["typology"] != "ecommerce" and not typology_override:
                T("tipología (corregida por evidencia estructural)", "ok",
                  f"{ctx['typology']} → ecommerce: hay fichas con Product schema, "
                  "y eso pesa más que el vocabulario de la home")
                ctx["typology"] = "ecommerce"
            # la evidencia estructural manda: que la re-evaluación por render
            # (que solo mira vocabulario) no la deshaga después
            ctx["typology_estructural"] = True
        else:
            # el intento fallido también se registra: silencio = agujero de fidelidad
            T("fichas de producto por contenido", "warn",
              f"sondeadas {len(sondeos)} URLs sin patrón de ficha (HTTP {sondeos}): "
              "ninguna con Product schema en el HTML crudo. Si el sitio es una "
              "tienda, sus fichas no son detectables automáticamente")
    ctx["sin_ficha_producto"] = (ctx["typology"] == "ecommerce"
                                 and not any(p["bucket"] == "producto" for p in pages))
    if ctx["sin_ficha_producto"]:
        T("cobertura de producto", "warn",
          "e-commerce sin NINGUNA ficha de producto en el muestreo: los checks que "
          "dependen de una ficha se marcan NO VERIFICABLES, no se puntúan a 0")

    if not skip_render:
        _log("render de la home (crudo vs JS + zonas de clic)…")
        ctx["rendered_home"] = render_page(base + "/", interactive=True)
        if ctx["rendered_home"].get("ok"):
            T("render JS", "ok",
              f"{len(ctx['rendered_home'].get('html', ''))} bytes: check 4.1 con comparación real")
        else:
            T("render JS", "fail",
              f"{ctx['rendered_home'].get('error', '?')[:150]} — 4.1 degrada a heurístico")

        # 4.7 en VARIAS plantillas: la home suele ser la página más cuidada del
        # sitio. Medir solo ahí daría un veredicto optimista que no representa
        # las fichas de producto ni las de servicio, que es donde el agente opera.
        _log("zonas de clic en otras plantillas…")
        ctx["rendered_pages"] = []
        vistos = set()
        for p in ctx["pages"]:
            if p["fetch"]["status"] != 200 or p["bucket"] in vistos:
                continue
            if len(ctx["rendered_pages"]) >= 2:   # techo de coste: +2 renders
                break
            vistos.add(p["bucket"])
            r = render_page(p["url"], interactive=True)
            if r.get("ok") and r.get("boxes"):
                ctx["rendered_pages"].append(
                    {"url": p["url"], "bucket": p["bucket"], "boxes": r["boxes"]})
        medidas = ([("home", ctx["rendered_home"].get("boxes") or [])]
                   if ctx["rendered_home"].get("boxes") else [])
        medidas += [(r["bucket"], r["boxes"]) for r in ctx["rendered_pages"]]
        if medidas:
            T("geometría de controles (4.7)", "ok",
              "medidas " + ", ".join(f"{n}: {len(b)} controles" for n, b in medidas))
        else:
            T("geometría de controles (4.7)", "warn",
              "el backend de render no devolvió geometría: 4.7 queda sin evidencia")
    else:
        ctx["rendered_home"] = None
        ctx["rendered_pages"] = []
        T("render JS", "skipped", "desactivado: checks 4.1 y 4.7 sin evidencia")

    _log("área de acceso (autenticación agéntica)…")
    ctx["login_probe"] = probe_login(base, ctx["home"]["body"], skip_render)
    lp = ctx["login_probe"]
    n_int = len(lp.get("intentos") or [])
    T("área de acceso", "ok",
      (f"login localizado en {lp['url']} (HTTP {lp['status']}, vía {lp.get('via')}) "
       f"tras probar {n_int} candidato(s)") if lp.get("found")
      else f"sin área de acceso accesible tras probar {n_int} candidato(s): 6.4 no aplica")

    _log("estados de error (soft-404)…")
    ctx["error_probe"] = probe_error_handling(base)
    ep = ctx["error_probe"]
    T("estados de error", "ok" if ep["status"] else "fail",
      f"URL inexistente -> HTTP {ep['status']}"
      + (" con texto de 'no encontrado'" if ep["looks_missing"] else "")
      + (" y vía de recuperación" if ep["has_recovery"] else ""))

    # Reafinar tipología con el HTML renderizado: en SPAs (Zara y similares) el
    # HTML crudo viene casi vacío y la detección se quedaría sin señales.
    rh = (ctx.get("rendered_home") or {}).get("html") or ""
    if not typology_override and not ctx.get("typology_estructural") \
            and len(rh) > len(ctx["home"].get("body", "")) * 1.2:
        typ2, ev2 = discovery.detect_typology(rh, all_urls)
        if typ2 != ctx["typology"]:
            T("tipología (re-evaluada con render)", "ok",
              f"{ctx['typology']} → {typ2} tras renderizar JS (la home cruda no tenía señales)")
            ctx["typology"], ctx["typology_evidence"] = typ2, ev2

    _log("negociación Markdown y DNS-AID…")
    md = fetch(base + "/", timeout=15, headers=["Accept: text/markdown"])
    ct = ""
    m = re.search(r"(?im)^content-type:\s*([^\r\n;]+)", md["headers"] or "")
    if m:
        ct = m.group(1).strip()
    body_is_md = (md["status"] == 200 and "<html" not in (md["body"] or "")[:300].lower()
                  and bool(re.search(r"(?m)^#{1,3} \S", (md["body"] or "")[:2000])))
    ctx["md_negotiation"] = {"content_type": ct, "is_markdown": "markdown" in ct.lower() or body_is_md}
    T("negociación Markdown", "ok" if md["status"] else "fail",
      f"Accept: text/markdown -> HTTP {md['status']}, {ct or '?'}")

    ctx["dns_aid"] = discovery.dns_aid(base)
    T("DNS-AID", "ok" if ctx["dns_aid"] else "ok",
      ctx["dns_aid"] or "consultados TXT _aid/_agent: sin registros (evidencia negativa válida)")

    _log("vista LLM (Jina)…")
    jina = jina_read(base + "/")
    ctx["jina_home_excerpt"] = (jina or "")[:3000]
    ctx["jina_ok"] = bool(jina)
    T("vista LLM (Jina)", "ok" if jina else "warn",
      f"{len(jina)} chars" if jina else "Jina sin contenido (rate limit/bloqueo)")

    ctx["psi_cls"] = psi_cls(base + "/") if with_psi else None
    if with_psi:
        T("PageSpeed (CLS)", "ok" if ctx["psi_cls"] is not None else "fail",
          f"CLS={ctx['psi_cls']}" if ctx["psi_cls"] is not None else "PSI sin respuesta")

    ctx.setdefault("agent_tests", None)
    return ctx


# Los nombres de categoría viven en catalog.py, que es la fuente de verdad
# del catálogo de factores. Tenerlos duplicados en tres módulos era pedir
# que se desincronizaran al renombrar una categoría.
from .catalog import CATEGORIES as CAT_NAMES


# Checks cuyo "0" significa "no lo he encontrado". Si el sitio nos ha bloqueado,
# ese 0 no es un hallazgo sobre la web: es una ceguera nuestra, y afirmarlo sería
# mentir. Se degradan a "no verificable" en vez de puntuar como fallo.
CHECKS_POR_AUSENCIA = {"1.4", "1.5", "1.7", "2.1", "2.3", "3.1", "3.2", "3.3",
                       "3.4", "3.5", "3.6", "4.5", "5.1", "5.2", "5.3", "5.5",
                       "5.6", "6.1", "6.2", "7.1", "7.5", "7.6"}
# Se quedan FUERA a propósito aunque el sitio bloquee: 1.6, 2.4 y 4.4 miden
# exactamente esa hostilidad al acceso automatizado, que es lo que un agente
# sufriría. Que el sitio nos bloquee ES el hallazgo, no ruido.

# Checks que leen MARCADO (JSON-LD, formularios, atributos). Si la home vino por
# un fallback de texto (Jina), el marcado sencillamente no está en lo que vemos:
# reportar "no tiene datos estructurados" sería describir nuestra vía de acceso,
# no la web del cliente.
CHECKS_DE_MARCADO = {"3.1", "3.2", "3.3", "3.4", "3.5", "3.6", "4.2", "6.2",
                     "7.1", "7.2", "7.5", "7.6"}

# Checks cuyo "no encontrado" depende de SONDAS adicionales (robots, sitemap,
# .well-known, negociación de contenido), no de la portada. Si la portada se vio
# pero esas sondas recibieron bloqueos, solo estas ausencias son inafirmables.
CHECKS_DE_SONDA = {"1.4", "1.5", "2.1", "4.5", "5.5", "5.6", "6.1"}


# Checks que NO pueden responderse sin abrir al menos una ficha de producto.
# 7.3 se queda fuera: mira el PSP en la home, no necesita ficha.
CHECKS_DE_FICHA = {"3.3", "4.2", "7.1", "7.2", "7.5", "7.6"}


def _degradar_sin_ficha_producto(results, ctx):
    """Un e-commerce cuyo catálogo no hemos sabido alcanzar no puntúa 0.

    Caso real (batería 5): zalando.de. Nuestros patrones de URL eran ES/EN, sus
    rutas son alemanas, y el muestreo terminó con buckets producto=0. Los checks
    de ficha se puntuaron 0 y el informe afirmaba "Sin JSON-LD Product en fichas
    muestreadas", "Ninguna ficha de producto accesible" y "Sin informacion de
    envio detectable, ni estructurada ni visible. Un agente que compare opciones
    descartara esta tienda" — sobre páginas que NUNCA abrimos. El score salía
    14.4 con score_fiable=True, listo para entregarse a un cliente.

    Ampliar los patrones (hecho) reduce el caso, pero no lo elimina: siempre
    habrá tiendas cuyo catálogo no alcancemos. La regla de fidelidad no puede
    depender de acertar el idioma. Si no vimos ficha, no afirmamos nada de ella.
    """
    if not ctx.get("sin_ficha_producto"):
        return results
    motivo = ("no se alcanzó ninguna ficha de producto en el muestreo, así que no "
              "es posible afirmar qué contienen las fichas de esta tienda. No es "
              "un defecto observado de la web: es una limitación de nuestra "
              "cobertura del catálogo")
    n = 0
    for r in results:
        if r["id"] in CHECKS_DE_FICHA and r["score"] == 0:
            r["score"] = None
            r["manual"] = True
            # marca explícita: el scoring necesita distinguir "aquí no hay nada
            # que medir" (no aplica, su peso se reparte) de "no hemos podido
            # medirlo" (no se reparte, o inflaría lo poco que quede en pie)
            r["no_verificable"] = True
            r["evidence"] = f"NO VERIFICABLE — {motivo}. (Sonda: {r['evidence'][:120]})"
            n += 1
    if n:
        ctx["cobertura_producto_degradada"] = {"degradados": n, "motivo": motivo}
        ctx["trail"].append({
            "step": "guardarraíl de cobertura de catálogo", "status": "warn",
            "detail": f"{n} checks de ficha degradados a 'no verificable'. {motivo}. "
                      f"La puntuación de C7 cubre solo lo comprobable desde la portada"})
    return results


def _cobertura_ciega(ctx):
    """¿Nos han servido una cáscara en lugar de la web?

    Caso real (batería 5, zalando.de en la segunda pasada): HTTP 200, 11 KB de
    portada, robots.txt correcto, _human=200… y CERO enlaces internos, CERO
    páginas muestreadas, CERO señales de tipología. El motor ya avisaba ("SIN
    señales: la web devuelve poco/ningún contenido a accesos automatizados")
    y aun así entregaba score 20.3 con score_fiable=True: todos los checks de
    contenido a 0 "por ausencia" sin haber visto una sola página.

    `_degradar_si_bloqueado` no lo cazaba porque solo mira que la portada pese
    >=500 bytes y que el UA humano reciba 200 — y una cáscara cumple ambas.
    La señal buena no es el peso: es que no hay NADA que rastrear.
    """
    if not ctx.get("cobertura_ciega"):
        return False
    ev = ctx.get("typology_evidence") or {}
    sin_senales = ((ev.get("ecommerce") or {}).get("puntos", 0) == 0
                   and (ev.get("saas") or {}).get("puntos", 0) == 0)
    return not ctx.get("pages") and sin_senales


def _veredicto_de_acceso(ctx):
    """¿Qué podemos AFIRMAR sobre el acceso, con la evidencia que tenemos?

    Antes esto era un único "puerta cerrada a agentes" que se disparaba solo con
    que nuestro UA de navegador no recibiera contenido — ignorando la matriz de
    bots, que ya tenía la mitad de la respuesta. Caso real: argal.com y noel.es
    salían "puerta cerrada" desde el servidor de producción y desde otra red
    servían 136 KB y 85 KB sin problema. Estábamos describiendo el bloqueo de un
    rango de IPs como si fuera la política del cliente hacia los agentes.

    Tres situaciones distintas:
      puerta_cerrada : vimos la web con navegador Y vimos que rechaza a los bots
                       de IA. Hallazgo agéntico, con las dos mitades probadas.
      no_evaluable   : no la pudimos leer, y los bots tampoco. No se distingue
                       "bloquea toda automatización" de "bloquea nuestra IP", así
                       que no se afirma ninguna de las dos.
      None           : se pudo leer (por navegador o rescatada como bot) y la
                       nota va por la escala normal.
    """
    bm = ctx.get("bot_matrix") or {}
    bots = {k: v for k, v in bm.items() if k != "_human"}
    algun_bot_entra = any(v == 200 for v in bots.values())
    humano_entra = bm.get("_human") == 200

    if humano_entra and bots and not algun_bot_entra:
        return "puerta_cerrada"
    if (ctx.get("acceso_degradado") or {}).get("nivel") == "total":
        return "no_evaluable"
    return None


def _degradar_si_bloqueado(results, ctx):
    """Si no hemos podido ver el sitio (o solo en parte), no afirmamos ausencias.
    Distinguir 'no está' de 'no lo he podido mirar' es la diferencia entre un
    informe fiable y uno que difama al cliente. Tres niveles:
      total   → no vimos nada creíble: se degrada todo lo basado en ausencia.
      marcado → solo texto vía Jina: se degrada lo que lee HTML + las sondas.
      sondas  → la portada SÍ se vio; solo fallaron sondas posteriores: se
                degradan únicamente las ausencias que dependen de ellas, y la
                puntuación sigue siendo utilizable (con aviso en el trail).
    """
    human = (ctx.get("bot_matrix") or {}).get("_human", 0)
    via = (ctx.get("home") or {}).get("_via", "http")
    home_status = (ctx.get("home") or {}).get("status", 0)
    # El peso NO acredita que hayamos visto la portada: una página de bloqueo de
    # WAF pesa de sobra. Caso real (batería 5, mediamarkt.es): HTTP 403 a TODAS
    # las peticiones (incluido el UA humano) con 13.656 bytes de "Access
    # Denied". Como el cuerpo pasaba el listón de 500 bytes y la vía seguía
    # siendo "http", se caía en la rama `else` y se etiquetaba nivel "sondas",
    # cuyo texto afirma "la portada se obtuvo con normalidad" y deja
    # score_fiable=True. Resultado entregable: mediamarkt.es = 🔴 "Invisible
    # para agentes. Riesgo alto", score 20.8 marcado como fiable, calculado
    # sobre la página de error del WAF. Es exactamente el sesgo que perseguimos:
    # culpar a la web ajena de nuestra propia ceguera.
    # Una portada es creíble si el servidor la dio por buena (200) o si la
    # rescatamos por otra vía (render/jina), que sí sustituyen el cuerpo.
    # "bot:<nombre>" = la portada se rescató leyéndola como un bot de IA que SÍ
    # recibe 200. Es contenido real del sitio, y además el más pertinente para
    # esta auditoría: es lo que el sitio le sirve a una IA.
    via_creible = via in ("render", "jina") or via.startswith("bot:")
    home_ok = (len((ctx.get("home") or {}).get("body") or "") >= 500
               and (home_status == 200 or via_creible))

    ciego = _cobertura_ciega(ctx)
    # La portada vale si la vimos como navegador con 200, o si la rescatamos
    # leyéndola como un bot de IA al que el sitio SÍ responde.
    acceso_ok = ((human == 200 and via in ("http", "render"))
                 or via.startswith("bot:"))
    if home_ok and acceso_ok and not ciego:
        ctx["acceso_degradado"] = None
        return results

    if ciego:
        # La cáscara es indistinguible de una web pobre MIRANDO EL PESO, pero no
        # mirando lo que contiene: sin un enlace, sin una página y sin una señal
        # de tipología, no hemos visto la web. Se degrada como bloqueo total y
        # la puntuación deja de ser entregable.
        nivel, objetivo = "total", CHECKS_POR_AUSENCIA
        motivo = (f"lo que el sitio sirve a un acceso automatizado no contiene ni un "
                  f"enlace interno ni señal alguna de su tipo de negocio (HTTP {human}, "
                  f"{len((ctx.get('home') or {}).get('body') or '')} bytes). No es una "
                  f"web vacía: es que no estamos viendo la web, así que ninguna "
                  f"ausencia es afirmable")
    elif not home_ok or (human != 200 and via == "render"):
        # sin portada creíble (un render con el humano bloqueado puede ser la
        # página del captcha: no nos fiamos de ese HTML)
        nivel, objetivo = "total", CHECKS_POR_AUSENCIA
        motivo = (f"el sitio no sirve contenido a un acceso automatizado (UA humano "
                  f"recibe HTTP {human}). No es posible afirmar que esto falte: no "
                  f"hemos podido comprobarlo")
    elif via == "jina":
        nivel, objetivo = "marcado", CHECKS_DE_MARCADO | CHECKS_DE_SONDA
        motivo = ("la página solo se pudo leer vía jina, que devuelve texto sin "
                  "marcado, y el acceso directo está limitado. El HTML real no es "
                  "observable, así que no afirmamos nada sobre él")
    else:
        # portada vista por HTTP normal, pero sondas posteriores bloqueadas
        nivel, objetivo = "sondas", CHECKS_DE_SONDA
        motivo = (f"la portada se obtuvo con normalidad, pero el sitio devolvió "
                  f"HTTP {human} a sondas posteriores del análisis: las ausencias "
                  f"que dependen de esas sondas no son afirmables")

    n = 0
    for r in results:
        if r["id"] not in objetivo:
            continue
        # Hasta aquí solo se degradaba `score == 0`: la ausencia inafirmable.
        # Pero cuando el cuerpo que hemos leído NO es la web (página de bloqueo
        # del WAF), una PRESENCIA es igual de inafirmable que una ausencia, y
        # además puntúa. Caso real (batería 6, bol.com y allegro.pl): ambas
        # devuelven 403 a todo; el check 3.6 leyó la página de "Access Denied",
        # no encontró elementos fantasma en ella y se anotó un 1. Como 3.6 era
        # el ÚNICO check de C3 que sobrevivía, C3 quedó en 1.0 con el peso más
        # alto del modelo (25) y allegro.pl salió con 64.5 y nivel
        # "Agent-aware": la MEJOR nota de toda la batería para un sitio que no
        # hemos visto. Los sitios que más nos bloquean puntuaban más alto.
        # Solo aplica a los niveles donde el propio contenido no es creíble
        # ("total" y "marcado"); en "sondas" la portada sí se vio y un >0
        # procede de una sonda que sí respondió, así que se respeta.
        contenido_no_creible = (nivel in ("total", "marcado")
                                and r["id"] in CHECKS_DE_MARCADO)
        if r["score"] == 0 or (contenido_no_creible and r["score"] is not None):
            r["score"] = None
            r["manual"] = True
            # marca explícita: el scoring necesita distinguir "aquí no hay nada
            # que medir" (no aplica, su peso se reparte) de "no hemos podido
            # medirlo" (no se reparte, o inflaría lo poco que quede en pie)
            r["no_verificable"] = True
            r["evidence"] = f"NO VERIFICABLE — {motivo}. (Sonda: {r['evidence'][:120]})"
            n += 1
    ctx["acceso_degradado"] = {"nivel": nivel, "motivo": motivo, "degradados": n,
                               "human_status": human, "via": via}
    if n:
        aviso_final = ("La puntuación global queda marcada como NO FIABLE: no debe "
                       "entregarse sin repetir el análisis"
                       if nivel in ("total", "marcado") else
                       "La puntuación sigue siendo utilizable: cubre lo que sí se "
                       "pudo comprobar")
        ctx["trail"].append({
            "step": "guardarraíl de fidelidad", "status": "warn",
            "detail": f"{n} checks degradados a 'no verificable' (nivel {nivel}). "
                      f"{motivo}. {aviso_final}"})
    return results


def audit_domain(base, typology_override=None, skip_render=False, with_psi=False,
                 categories=None, with_agents=False, allow_submit=False,
                 check_ids=None, agent_repeticiones=3, agentes_pendientes=False):
    """Audita un dominio y devuelve el dict de resultados (apto para JSON/UI)."""
    base = discovery.normalize(base)
    assert_public_url(base)  # anti-SSRF antes de nada
    ctx = gather_context(base, typology_override, skip_render, with_psi)
    # las pruebas agenticas se lanzan aparte desde el informe: el check 6.3 lo
    # dice asi en vez de pedir que se active algo que ya esta activado
    ctx["agentes_pendientes"] = bool(agentes_pendientes) and not with_agents

    if with_agents:
        _log("pruebas agénticas reales (varios minutos)…")
        try:
            from .agents import run_agent_tests
            ctx["agent_tests"] = run_agent_tests(
                base, ctx["typology"], allow_submit=allow_submit, log=LOG_SINK,
                repeticiones=agent_repeticiones)
            agents = ctx["agent_tests"].get("agents", {})
            ran = [k for k, v in agents.items() if v.get("outcome") != "no_disponible"]
            det = (f"agentes ejecutados: {', '.join(ran) or 'ninguno'}"
                   f" · {ctx['agent_tests'].get('repeticiones')} intentos por agente")
            if allow_submit:
                det += " [envío de formularios AUTORIZADO en este dominio]"
            ctx["trail"].append({"step": "pruebas agénticas (6.3)",
                                 "status": "ok" if ran else "fail", "detail": det})
        except Exception as exc:
            ctx["agent_tests"] = None
            ctx["trail"].append({"step": "pruebas agénticas (6.3)", "status": "fail",
                                 "detail": str(exc)[:200]})
    else:
        ctx["trail"].append({"step": "pruebas agénticas (6.3)", "status": "skipped",
                             "detail": "desactivadas: el check 6.3 queda como manual"})

    # La sonda de rate limiting va la ULTIMA de todas a propósito: aporrear el
    # sitio con 10 peticiones seguidas al principio contaminaba las mediciones
    # posteriores (muestreo, render, sondas e incluso las pruebas agénticas) en
    # sitios con límite por IP. Detectado en calibración: perfumesclub devolvió
    # 429/418 al muestreo tras dispararse esta sonda, y acabamos baneados.
    _log("rate limiting (última sonda, para no contaminar el resto)…")
    ctx["rapid"] = rapid_fire(base + "/", BOT_UAS["GPTBot"], n=10)
    ctx["trail"].append({"step": "rate limiting", "status": "ok",
                         "detail": f"10 peticiones como GPTBot: {ctx['rapid']} "
                                   "(se ejecuta al final para no distorsionar las demás sondas)"})

    results = checks_mod.run_all(ctx)
    results = _degradar_sin_ficha_producto(results, ctx)
    results = _degradar_si_bloqueado(results, ctx)
    if categories:
        results = [r for r in results if r["cat"] in categories]
    if check_ids:
        results = [r for r in results if r["id"] in check_ids]

    total, cat_scores, weights, cobertura = scoring.total_score(results, ctx["typology"])
    adjusted, penalties = scoring.apply_governance_gate(total, results, ctx["typology"])
    level = scoring.level_for(adjusted, veredicto=_veredicto_de_acceso(ctx))

    from .knowledge import advice_for
    for r in results:
        if r["score"] is not None and r["score"] < 1:
            r["advice"] = advice_for(r["id"])

    return {
        "domain": base,
        "host": urlparse(base).netloc.replace("www.", ""),
        "typology": ctx["typology"],
        "typology_evidence": ctx["typology_evidence"],
        "score": adjusted,
        "score_pre_gate": total,
        "penalties": penalties,
        "level": level,
        "category_scores": cat_scores,
        "category_weights": {k: round(v, 1) for k, v in weights.items()},
        # qué parte del modelo cubre de verdad esta nota (1.0 = todo lo que
        # aplica). Baja cuando hay categorías que NO pudimos medir, y su peso
        # ya no se reparte sobre las demás para no inflarlas.
        "cobertura_score": cobertura,
        "checks": results,
        "bot_matrix": ctx["bot_matrix"],
        "buckets": ctx["buckets_size"],
        "pages_sampled": [{"url": p["url"], "bucket": p["bucket"],
                           "status": p["fetch"]["status"],
                           "via": p["fetch"].get("_via", "http")} for p in ctx["pages"]],
        "wellknown": {k: v for k, v in ctx["wellknown"].items() if v == 200},
        "jina_ok": ctx["jina_ok"],
        "render_ok": bool(ctx.get("rendered_home") and ctx["rendered_home"].get("ok")),
        # "sondas" degrada checks concretos pero la puntuación sigue valiendo;
        # solo "total" y "marcado" invalidan el score para entrega
        "score_fiable": (ctx.get("acceso_degradado") or {}).get("nivel")
                        not in ("total", "marcado"),
        "acceso_degradado": ctx.get("acceso_degradado"),
        # Presente solo si es una tienda cuyo catálogo no alcanzamos: la UI y el
        # PDF deben poder decir "C7 incompleto" en vez de "C7 suspende"
        "cobertura_producto_degradada": ctx.get("cobertura_producto_degradada"),
        "error_handling": ctx.get("error_probe"),
        "login_area": {k: v for k, v in (ctx.get("login_probe") or {}).items()
                       if k != "body"},
        "interactive_controls": len((ctx.get("rendered_home") or {}).get("boxes") or []),
        "agent_tests": ctx.get("agent_tests"),
        "trail": ctx["trail"],
        "coverage": {
            "sitemap_urls": len(ctx["sitemap"]["urls"]),
            "sampled": len(ctx["pages"]),
            "sampled_ok": sum(1 for p in ctx["pages"] if p["fetch"]["status"] == 200),
            "fallbacks": sum(1 for p in ctx["pages"] if p["fetch"].get("_via")),
            "buckets": ctx["buckets_size"],
        },
    }


def run_audit(urls, typology=None, skip_render=False, with_psi=False,
              categories=None, log=None):
    """Audita cliente + competidores. Devuelve el dict 'data' completo para la UI."""
    global LOG_SINK
    if log is not None:
        LOG_SINK = log
    audits = []
    try:
        for u in urls[:3]:
            try:
                audits.append(audit_domain(u, typology, skip_render, with_psi, categories))
            except Exception as exc:
                audits.append({"domain": u, "error": str(exc)[:200]})
    finally:
        LOG_SINK = None
    return {
        "client": audits[0] if audits else None,
        "competitors": audits[1:],
        "framework_version": "2.0 (agent_scanner, integrado en clicandseo)",
    }
